import { buildPackFromDefs, type PackScenarioDef } from "./types"

const DEFAULT_OPTS = [
  "continuation",
  "reversal",
  "break-retest",
  "no-trade",
] as const

const DEFS: PackScenarioDef[] = [
  {
    id: "pack-cont-01-healthy-trend",
    title: "Healthy Trend Continuation",
    description: "Clean HH/HL uptrend with shallow pullback. Is structure still bullish?",
    symbol: "EURUSD",
    kind: "uptrend",
    seed: "pack-cont-01",
    category: "continuation",
    difficulty: "Beginner",
    correctTrend: "uptrend",
    bestStrategy: "continuation",
    strategyOptions: [...DEFAULT_OPTS],
    idealDirection: "buy",
    behaviour: "continuation",
    subcategory: "healthy-trend",
    tags: ["continuation", "healthy-trend", "beginner"],
    session: "London",
    hints: ["HH/HL sequence intact", "Pullback is shallow — not a reversal", "Wait for rejection before entry"],
    commonMistakes: ["Buying the first red candle", "Calling reversal too early"],
    journalPrompt: "What confirmed the trend was still healthy?",
  },
  {
    id: "pack-cont-02-pullback-hold",
    title: "Pullback Holds Structure",
    description: "Price dips to prior swing low in an uptrend. Continuation or break?",
    symbol: "EURUSD",
    kind: "uptrend",
    seed: "pack-cont-02",
    category: "continuation",
    difficulty: "Beginner",
    correctTrend: "uptrend",
    bestStrategy: "continuation",
    strategyOptions: [...DEFAULT_OPTS],
    idealDirection: "buy",
    behaviour: "continuation",
    subcategory: "pullback",
    tags: ["continuation", "pullback", "beginner"],
    session: "London",
    hints: ["Prior swing low should hold", "No LH yet — trend intact", "Enter on bullish rejection"],
    commonMistakes: ["Entering before the low is tested", "Placing stop too tight"],
    journalPrompt: "Where was invalidation for this pullback?",
  },
  {
    id: "pack-cont-03-eurusd-trend",
    title: "EURUSD Trend Resume",
    description: "EURUSD consolidates under highs then resumes. Buy or wait?",
    symbol: "EURUSD",
    kind: "uptrend",
    seed: "pack-cont-03",
    category: "continuation",
    difficulty: "Beginner",
    correctTrend: "uptrend",
    bestStrategy: "continuation",
    strategyOptions: [...DEFAULT_OPTS],
    idealDirection: "buy",
    behaviour: "continuation",
    subcategory: "eurusd",
    tags: ["continuation", "eurusd", "beginner"],
    session: "London",
    hints: ["Consolidation under highs is bullish", "Don't chase breakouts", "Stop below consolidation"],
    commonMistakes: ["Chasing mid-impulse", "Ignoring spread at London open"],
    journalPrompt: "Why was this EURUSD continuation, not range?",
  },
  {
    id: "pack-cont-04-support-bounce",
    title: "Support Bounce Continuation",
    description: "Uptrend rejects rising support. Buy the bounce?",
    symbol: "EURUSD",
    kind: "support-bounce",
    seed: "pack-cont-04",
    category: "continuation",
    difficulty: "Beginner",
    correctTrend: "uptrend",
    bestStrategy: "continuation",
    strategyOptions: [...DEFAULT_OPTS, "range"],
    idealDirection: "buy",
    behaviour: "continuation",
    subcategory: "support-bounce",
    tags: ["continuation", "support", "beginner"],
    session: "Asian",
    hints: ["Support in uptrend = higher low zone", "Wick rejection adds confluence", "Stop below swing low"],
    commonMistakes: ["Buying into resistance", "Stop inside the noise"],
    journalPrompt: "How did support confirm continuation?",
  },
  {
    id: "pack-cont-05-shallow-dip",
    title: "Shallow Dip — Don't Buy Early",
    description: "Pullback still developing. Enter now or wait for confirmation?",
    symbol: "GBPUSD",
    kind: "uptrend",
    seed: "pack-cont-05",
    category: "continuation",
    difficulty: "Beginner",
    correctTrend: "uptrend",
    bestStrategy: "continuation",
    strategyOptions: [...DEFAULT_OPTS],
    idealDirection: "wait",
    behaviour: "continuation",
    subcategory: "early-entry-trap",
    tags: ["continuation", "patience", "beginner"],
    session: "London",
    hints: ["Pullback may not be complete", "Professionals wait for rejection candle", "Trend intact but timing matters"],
    commonMistakes: ["Buying too early in the pullback", "FOMO on green candles"],
    journalPrompt: "Why was waiting better than buying immediately?",
  },
  {
    id: "pack-cont-06-ema-pullback",
    title: "EMA Zone Pullback",
    description: "Trend pulls back to dynamic support area. Continuation entry?",
    symbol: "EURUSD",
    kind: "uptrend",
    seed: "pack-cont-06",
    category: "continuation",
    difficulty: "Intermediate",
    correctTrend: "uptrend",
    bestStrategy: "continuation",
    strategyOptions: [...DEFAULT_OPTS],
    idealDirection: "buy",
    behaviour: "continuation",
    subcategory: "ema-pullback",
    tags: ["continuation", "ema", "intermediate"],
    session: "London",
    hints: ["Dynamic support often aligns with structure", "Pullback depth matters", "Confirm with bullish close"],
    commonMistakes: ["Treating every touch as automatic entry", "Ignoring structure for indicators"],
    journalPrompt: "How did structure and momentum align?",
  },
  {
    id: "pack-cont-07-break-retest",
    title: "Break & Retest Continuation",
    description: "Breakout pulls back to broken resistance. Enter the retest?",
    symbol: "EURUSD",
    kind: "break-retest",
    seed: "pack-cont-07",
    category: "continuation",
    difficulty: "Intermediate",
    correctTrend: "uptrend",
    bestStrategy: "break-retest",
    strategyOptions: ["break-retest", "continuation", "reversal", "no-trade"],
    idealDirection: "buy",
    behaviour: "continuation",
    subcategory: "break-retest",
    tags: ["continuation", "break-retest", "intermediate"],
    session: "New York",
    hints: ["Broken resistance becomes support", "Wait for retest rejection", "Don't chase initial breakout"],
    commonMistakes: ["Entering on breakout candle", "Stop above retest zone"],
    journalPrompt: "Why is break-retest a continuation playbook?",
  },
  {
    id: "pack-cont-08-london-impulse",
    title: "London Session Continuation",
    description: "London impulse extends the Asian trend. Ride or wait?",
    symbol: "GBPUSD",
    kind: "uptrend",
    seed: "pack-cont-08",
    category: "continuation",
    difficulty: "Intermediate",
    correctTrend: "uptrend",
    bestStrategy: "continuation",
    strategyOptions: [...DEFAULT_OPTS],
    idealDirection: "buy",
    behaviour: "continuation",
    subcategory: "london-continuation",
    tags: ["continuation", "london", "gbpusd", "intermediate"],
    session: "London",
    hints: ["London often extends overnight bias", "Look for shallow pullback first", "Session momentum matters"],
    commonMistakes: ["Fading London open without reason", "Oversizing on volatility spike"],
    journalPrompt: "How did London session context support continuation?",
  },
  {
    id: "pack-cont-09-gbpusd-trend",
    title: "GBPUSD Momentum Continuation",
    description: "Cable trends with strong momentum. Join or miss it?",
    symbol: "GBPUSD",
    kind: "uptrend",
    seed: "pack-cont-09",
    category: "continuation",
    difficulty: "Intermediate",
    correctTrend: "uptrend",
    bestStrategy: "continuation",
    strategyOptions: [...DEFAULT_OPTS],
    idealDirection: "buy",
    behaviour: "continuation",
    subcategory: "gbpusd",
    tags: ["continuation", "gbpusd", "momentum", "intermediate"],
    session: "New York",
    hints: ["Strong momentum = shallow pullbacks", "Enter on pause, not chase", "Wider stop in volatile pairs"],
    commonMistakes: ["Chasing extended moves", "Tight stops in GBP volatility"],
    journalPrompt: "How did you time entry in strong momentum?",
  },
  {
    id: "pack-cont-10-momentum-leg",
    title: "Momentum Leg Continuation",
    description: "Third impulse leg in a trend. Continuation or exhaustion?",
    symbol: "EURUSD",
    kind: "breakout",
    seed: "pack-cont-10",
    category: "continuation",
    difficulty: "Intermediate",
    correctTrend: "uptrend",
    bestStrategy: "continuation",
    strategyOptions: [...DEFAULT_OPTS],
    idealDirection: "buy",
    behaviour: "continuation",
    subcategory: "momentum",
    tags: ["continuation", "momentum", "intermediate"],
    session: "New York",
    hints: ["Third leg can still continue in trends", "Watch for divergence at extremes", "Trail stop on strong trends"],
    commonMistakes: ["Assuming exhaustion too early", "No stop management plan"],
    journalPrompt: "What told you momentum wasn't exhausted yet?",
  },
  {
    id: "pack-cont-11-ny-extension",
    title: "New York Extension",
    description: "NY session extends London move. Continuation trade?",
    symbol: "USDJPY",
    kind: "uptrend",
    seed: "pack-cont-11",
    category: "continuation",
    difficulty: "Advanced",
    correctTrend: "uptrend",
    bestStrategy: "continuation",
    strategyOptions: [...DEFAULT_OPTS],
    idealDirection: "buy",
    behaviour: "continuation",
    subcategory: "new-york-continuation",
    tags: ["continuation", "new-york", "usdjpy", "advanced"],
    session: "New York",
    hints: ["NY often extends London direction", "JPY pairs move fast — size down", "Pullback to structure preferred"],
    commonMistakes: ["Reversal trading against session flow", "Ignoring pip value on JPY"],
    journalPrompt: "How did NY session align with the trend?",
  },
  {
    id: "pack-cont-12-gold-trend",
    title: "Gold Trend Continuation",
    description: "XAUUSD trends with shallow dips. Buy pullback in gold?",
    symbol: "XAUUSD",
    kind: "support-bounce",
    seed: "pack-cont-12",
    category: "continuation",
    difficulty: "Advanced",
    correctTrend: "uptrend",
    bestStrategy: "continuation",
    strategyOptions: [...DEFAULT_OPTS],
    idealDirection: "buy",
    behaviour: "continuation",
    subcategory: "gold-continuation",
    tags: ["continuation", "gold", "advanced"],
    session: "London",
    hints: ["Gold trends can run further than FX", "Size smaller — volatility is high", "Support bounces in trends are valid"],
    commonMistakes: ["FX position sizing on gold", "Tight stops get swept"],
    journalPrompt: "What adjustments did gold volatility require?",
  },
  {
    id: "pack-cont-13-strong-momentum",
    title: "Strong Momentum Day",
    description: "Trend day with minimal pullbacks. How do professionals enter?",
    symbol: "GBPUSD",
    kind: "breakout",
    seed: "pack-cont-13",
    category: "continuation",
    difficulty: "Advanced",
    correctTrend: "uptrend",
    bestStrategy: "continuation",
    strategyOptions: [...DEFAULT_OPTS],
    idealDirection: "buy",
    behaviour: "continuation",
    subcategory: "strong-momentum",
    tags: ["continuation", "trend-day", "advanced"],
    session: "New York",
    hints: ["Trend days = shallow pullbacks only", "Enter on micro pullbacks", "Don't fade strength without structure break"],
    commonMistakes: ["Waiting for deep pullbacks that never come", "Counter-trend entries"],
    journalPrompt: "How do you trade strong momentum without chasing?",
  },
  {
    id: "pack-cont-14-deep-pullback-hold",
    title: "Deep Pullback Still Valid",
    description: "Deeper correction but HH/HL intact. Continuation or reversal forming?",
    symbol: "EURUSD",
    kind: "uptrend",
    seed: "pack-cont-14",
    category: "continuation",
    difficulty: "Advanced",
    correctTrend: "uptrend",
    bestStrategy: "continuation",
    strategyOptions: [...DEFAULT_OPTS],
    idealDirection: "buy",
    behaviour: "continuation",
    subcategory: "deep-pullback",
    tags: ["continuation", "deep-pullback", "advanced"],
    session: "London",
    hints: ["Deep pullback ≠ reversal if HL holds", "Need bullish confirmation", "Wider stop for deeper pullbacks"],
    commonMistakes: ["Confusing deep pullback with reversal", "Stop too tight for volatility"],
    journalPrompt: "What proved structure was still bullish?",
    reversalGrade: "B",
  },
  {
    id: "pack-cont-15-pro-trend-day",
    title: "Professional Trend Day",
    description: "Institutional trend day — one direction dominates. Execute or observe?",
    symbol: "EURUSD",
    kind: "uptrend",
    seed: "pack-cont-15",
    category: "continuation",
    difficulty: "Professional",
    correctTrend: "uptrend",
    bestStrategy: "continuation",
    strategyOptions: [...DEFAULT_OPTS],
    idealDirection: "buy",
    behaviour: "continuation",
    subcategory: "trend-day",
    tags: ["continuation", "trend-day", "professional"],
    session: "New York",
    hints: ["Trend days favour with-trend only", "Best entries on brief pauses", "Avoid counter-trend entirely"],
    commonMistakes: ["Overtrading both sides", "Missing the trend day read"],
    journalPrompt: "How did you identify this as a trend day early?",
    reversalGrade: "A",
  },
  {
    id: "pack-cont-16-late-pullback",
    title: "Late Pullback Entry",
    description: "Pullback completes at key level. Precision entry required.",
    symbol: "GBPUSD",
    kind: "uptrend",
    seed: "pack-cont-16",
    category: "continuation",
    difficulty: "Professional",
    correctTrend: "uptrend",
    bestStrategy: "continuation",
    strategyOptions: [...DEFAULT_OPTS],
    idealDirection: "buy",
    behaviour: "continuation",
    subcategory: "precision-entry",
    tags: ["continuation", "precision", "professional"],
    session: "London",
    hints: ["Wait for exact rejection at structure", "R:R must justify entry", "Patience separates pros from amateurs"],
    commonMistakes: ["Entering before confirmation close", "Poor R:R on late entries"],
    journalPrompt: "What made this a high-quality continuation entry?",
    reversalGrade: "A",
  },
  {
    id: "pack-cont-17-multi-leg",
    title: "Multi-Leg Trend Structure",
    description: "Three clear impulse legs. Fourth leg continuation?",
    symbol: "EURUSD",
    kind: "uptrend",
    seed: "pack-cont-17",
    category: "continuation",
    difficulty: "Professional",
    correctTrend: "uptrend",
    bestStrategy: "continuation",
    strategyOptions: [...DEFAULT_OPTS],
    idealDirection: "buy",
    behaviour: "continuation",
    subcategory: "multi-leg",
    tags: ["continuation", "multi-leg", "professional"],
    session: "New York",
    hints: ["Count the legs — exhaustion risk rises", "Tighter management on later legs", "Structure still rules"],
    commonMistakes: ["Assuming infinite continuation", "No exit plan on extended trends"],
    journalPrompt: "When do you reduce size on extended trends?",
    reversalGrade: "A",
  },
  {
    id: "pack-cont-18-br-pro",
    title: "Professional Break & Retest",
    description: "Clean break, patient retest, institutional entry zone.",
    symbol: "XAUUSD",
    kind: "break-retest",
    seed: "pack-cont-18",
    category: "continuation",
    difficulty: "Professional",
    correctTrend: "uptrend",
    bestStrategy: "break-retest",
    strategyOptions: ["break-retest", "continuation", "no-trade"],
    idealDirection: "buy",
    behaviour: "continuation",
    subcategory: "break-retest-pro",
    tags: ["continuation", "break-retest", "gold", "professional"],
    session: "London",
    hints: ["Institutions wait for retest", "Gold retests can be violent — size accordingly", "Confirmation candle required"],
    commonMistakes: ["Market ordering the breakout", "Undersized stops on gold"],
    journalPrompt: "Why is break-retest the institutional continuation entry?",
    reversalGrade: "A+",
  },
  {
    id: "pack-cont-19-london-open",
    title: "London Open Continuation",
    description: "London open extends overnight trend with liquidity sweep then resume.",
    symbol: "GBPUSD",
    kind: "uptrend",
    seed: "pack-cont-19",
    category: "continuation",
    difficulty: "Professional",
    correctTrend: "uptrend",
    bestStrategy: "continuation",
    strategyOptions: [...DEFAULT_OPTS, "liquidity-sweep"],
    idealDirection: "buy",
    behaviour: "continuation",
    subcategory: "london-open",
    tags: ["continuation", "london-open", "professional"],
    session: "London",
    hints: ["London open often sweeps then continues", "Wait for sweep completion", "Session liquidity creates opportunity"],
    commonMistakes: ["Trading the sweep as reversal", "Entering before sweep completes"],
    journalPrompt: "How did London open liquidity support continuation?",
    reversalGrade: "A",
  },
  {
    id: "pack-cont-20-institutional",
    title: "Institutional Continuation",
    description: "Textbook institutional trend — structure, session, and momentum align.",
    symbol: "EURUSD",
    kind: "uptrend",
    seed: "pack-cont-20",
    category: "continuation",
    difficulty: "Professional",
    correctTrend: "uptrend",
    bestStrategy: "continuation",
    strategyOptions: [...DEFAULT_OPTS],
    idealDirection: "buy",
    behaviour: "continuation",
    subcategory: "institutional",
    tags: ["continuation", "institutional", "professional"],
    session: "New York",
    hints: ["All timeframes aligned", "Enter on shallow pullback only", "This is an A+ continuation setup"],
    commonMistakes: ["Overcomplicating a clean setup", "Taking profit too early on A+ trades"],
    journalPrompt: "Full professional workflow — what made this A+?",
    reversalGrade: "A+",
  },
]

export const CONTINUATION_ACADEMY_SCENARIOS = buildPackFromDefs("continuation", DEFS)
