import { buildPackFromDefs, type PackScenarioDef } from "./types"

const EOD_OPTS = ["continuation", "reversal", "liquidity-sweep", "no-trade"] as const

const DEFS: PackScenarioDef[] = [
  {
    id: "pack-eod-01-strong-daily-cont",
    title: "Strong Daily Continuation",
    description: "Daily trend strong — intraday pullback is continuation opportunity.",
    symbol: "EURUSD",
    kind: "uptrend",
    seed: "pack-eod-01",
    category: "continuation",
    difficulty: "Beginner",
    correctTrend: "uptrend",
    bestStrategy: "continuation",
    strategyOptions: [...EOD_OPTS],
    idealDirection: "buy",
    behaviour: "continuation",
    subcategory: "daily-continuation",
    tags: ["eod", "daily-bias", "continuation", "beginner"],
    session: "New York Close",
    hints: ["Daily bias first — execution second", "Intraday pullback in daily trend", "EOD can still continue"],
    commonMistakes: ["Ignoring daily chart", "Counter-trend intraday entries"],
    journalPrompt: "How did daily context support continuation?",
  },
  {
    id: "pack-eod-02-weak-continuation",
    title: "Weak EOD Continuation",
    description: "Daily trend weakening — continuation risky near close.",
    symbol: "EURUSD",
    kind: "uptrend",
    seed: "pack-eod-02",
    category: "continuation",
    difficulty: "Beginner",
    correctTrend: "uptrend",
    bestStrategy: "no-trade",
    strategyOptions: [...EOD_OPTS],
    idealDirection: "wait",
    behaviour: "continuation",
    subcategory: "weak-continuation",
    tags: ["eod", "weak-continuation", "beginner"],
    session: "New York Close",
    hints: ["Weak daily momentum near close", "Risk/reward poor into EOD", "Standing aside is valid"],
    commonMistakes: ["Forcing continuation into close", "Ignoring momentum fade"],
    journalPrompt: "Why was weak continuation a no-trade?",
  },
  {
    id: "pack-eod-03-trend-day",
    title: "EOD Trend Day",
    description: "One-direction trend day into the close. Continue or flatten?",
    symbol: "GBPUSD",
    kind: "breakout",
    seed: "pack-eod-03",
    category: "continuation",
    difficulty: "Beginner",
    correctTrend: "uptrend",
    bestStrategy: "continuation",
    strategyOptions: [...EOD_OPTS],
    idealDirection: "buy",
    behaviour: "continuation",
    subcategory: "trend-day",
    tags: ["eod", "trend-day", "beginner"],
    session: "New York Close",
    hints: ["Trend days often close strong", "Don't fade trend days at EOD", "Size down near close"],
    commonMistakes: ["Fading trend day close", "Oversizing into EOD volatility"],
    journalPrompt: "How do you trade trend day closes?",
  },
  {
    id: "pack-eod-04-momentum-close",
    title: "Momentum Into Close",
    description: "Strong momentum into NY close. Ride or take profit?",
    symbol: "USDJPY",
    kind: "uptrend",
    seed: "pack-eod-04",
    category: "continuation",
    difficulty: "Beginner",
    correctTrend: "uptrend",
    bestStrategy: "continuation",
    strategyOptions: [...EOD_OPTS],
    idealDirection: "buy",
    behaviour: "continuation",
    subcategory: "momentum-close",
    tags: ["eod", "momentum", "beginner"],
    session: "New York Close",
    hints: ["Momentum close can extend", "Trail stop tightly", "Watch for exhaustion wick"],
    commonMistakes: ["No exit plan into close", "Holding through spread widening"],
    journalPrompt: "When do you take profit before close?",
  },
  {
    id: "pack-eod-05-daily-context",
    title: "Daily Context First",
    description: "Read daily structure before any EOD execution decision.",
    symbol: "EURUSD",
    kind: "uptrend",
    seed: "pack-eod-05",
    category: "continuation",
    difficulty: "Beginner",
    correctTrend: "uptrend",
    bestStrategy: "continuation",
    strategyOptions: [...EOD_OPTS],
    idealDirection: "buy",
    behaviour: "continuation",
    subcategory: "daily-context",
    tags: ["eod", "daily-context", "beginner"],
    session: "New York Close",
    hints: ["Always start with daily chart", "HTF sets the playbook", "LTF is for timing only"],
    commonMistakes: ["LTF-only analysis", "Missing daily resistance"],
    journalPrompt: "What did daily structure tell you before executing?",
  },
  {
    id: "pack-eod-06-exhaustion-fade",
    title: "EOD Exhaustion Fade",
    description: "Session impulse exhausts into close. Fade or flat?",
    symbol: "EURUSD",
    kind: "downtrend-reversal",
    seed: "pack-eod-06",
    category: "reversal",
    difficulty: "Intermediate",
    correctTrend: "uptrend",
    bestStrategy: "reversal",
    strategyOptions: [...EOD_OPTS],
    idealDirection: "buy",
    behaviour: "reversal",
    subcategory: "eod-exhaustion",
    tags: ["eod", "exhaustion", "reversal", "intermediate"],
    session: "New York Close",
    hints: ["EOD often fades session impulse", "Look for sweep then rejection", "Tight stop — volatility spikes"],
    commonMistakes: ["Chasing the close", "Wide stops in EOD volatility"],
    journalPrompt: "How did session exhaustion signal reversal?",
    reversalGrade: "A",
  },
  {
    id: "pack-eod-07-liquidity-sweep",
    title: "EOD Liquidity Sweep",
    description: "Price sweeps session highs/lows into close then reverses.",
    symbol: "GBPUSD",
    kind: "fakeout",
    seed: "pack-eod-07",
    category: "reversal",
    difficulty: "Intermediate",
    correctTrend: "downtrend",
    bestStrategy: "liquidity-sweep",
    strategyOptions: [...EOD_OPTS],
    idealDirection: "sell",
    behaviour: "reversal",
    subcategory: "eod-liquidity-sweep",
    tags: ["eod", "liquidity-sweep", "intermediate"],
    session: "New York Close",
    hints: ["EOD liquidity grabs are common", "Stops cluster at session extremes", "Wait for rejection after sweep"],
    commonMistakes: ["Trading the sweep direction", "No confirmation after grab"],
    journalPrompt: "How did you identify the EOD liquidity sweep?",
    reversalGrade: "A",
  },
  {
    id: "pack-eod-08-daily-bos",
    title: "Daily BOS at Close",
    description: "Daily structure breaks on the closing impulse.",
    symbol: "EURUSD",
    kind: "uptrend-reversal",
    seed: "pack-eod-08",
    category: "reversal",
    difficulty: "Intermediate",
    correctTrend: "downtrend",
    bestStrategy: "reversal",
    strategyOptions: [...EOD_OPTS],
    idealDirection: "sell",
    behaviour: "reversal",
    subcategory: "daily-bos",
    tags: ["eod", "bos", "daily", "intermediate"],
    session: "New York Close",
    hints: ["Daily BOS changes tomorrow's bias", "EOD break can be violent", "Confirm on daily close"],
    commonMistakes: ["Trading intraday BOS as daily", "Ignoring wick vs body close"],
    journalPrompt: "What confirmed daily structure break?",
    reversalGrade: "A",
  },
  {
    id: "pack-eod-09-htf-rejection",
    title: "HTF Rejection at EOD",
    description: "Price rejects daily/4H level into the close.",
    symbol: "XAUUSD",
    kind: "resistance-rejection",
    seed: "pack-eod-09",
    category: "reversal",
    difficulty: "Intermediate",
    correctTrend: "downtrend",
    bestStrategy: "reversal",
    strategyOptions: [...EOD_OPTS],
    idealDirection: "sell",
    behaviour: "reversal",
    subcategory: "htf-rejection",
    tags: ["eod", "htf-rejection", "gold", "intermediate"],
    session: "New York Close",
    hints: ["HTF rejection at EOD is powerful", "Gold respects daily levels", "Size down — gold is volatile"],
    commonMistakes: ["Ignoring daily resistance", "Oversizing gold EOD trades"],
    journalPrompt: "How did HTF level create EOD reversal?",
    reversalGrade: "B",
  },
  {
    id: "pack-eod-10-late-fade",
    title: "Late Session Fade",
    description: "NY afternoon fade after morning impulse.",
    symbol: "EURUSD",
    kind: "downtrend-reversal",
    seed: "pack-eod-10",
    category: "reversal",
    difficulty: "Intermediate",
    correctTrend: "uptrend",
    bestStrategy: "reversal",
    strategyOptions: [...EOD_OPTS],
    idealDirection: "buy",
    behaviour: "reversal",
    subcategory: "late-fade",
    tags: ["eod", "late-fade", "intermediate"],
    session: "New York Close",
    hints: ["Afternoon often fades morning move", "Look for liquidity sweep low", "Session timing is key"],
    commonMistakes: ["Trading morning bias into afternoon", "Ignoring session phases"],
    journalPrompt: "How did session phase change the playbook?",
    reversalGrade: "A",
  },
  {
    id: "pack-eod-11-gold-eod-rev",
    title: "Gold EOD Reversal",
    description: "XAUUSD spikes into close then reverses sharply.",
    symbol: "XAUUSD",
    kind: "resistance-rejection",
    seed: "pack-eod-11",
    category: "reversal",
    difficulty: "Advanced",
    correctTrend: "downtrend",
    bestStrategy: "reversal",
    strategyOptions: [...EOD_OPTS],
    idealDirection: "sell",
    behaviour: "reversal",
    subcategory: "gold-eod-reversal",
    tags: ["eod", "gold", "reversal", "advanced"],
    session: "New York Close",
    hints: ["Gold EOD spikes trap retail", "Institutional fade at extremes", "Tight stop above sweep"],
    commonMistakes: ["Chasing gold spikes", "FX sizing on gold"],
    journalPrompt: "What made this a gold-specific EOD reversal?",
    reversalGrade: "A+",
  },
  {
    id: "pack-eod-12-eurusd-eod",
    title: "EURUSD EOD Workflow",
    description: "Full EOD workflow on EURUSD — context, structure, execution.",
    symbol: "EURUSD",
    kind: "downtrend-reversal",
    seed: "pack-eod-12",
    category: "reversal",
    difficulty: "Advanced",
    correctTrend: "uptrend",
    bestStrategy: "reversal",
    strategyOptions: [...EOD_OPTS],
    idealDirection: "buy",
    behaviour: "reversal",
    subcategory: "eurusd-eod",
    tags: ["eod", "eurusd", "workflow", "advanced"],
    session: "New York Close",
    hints: ["Daily → 4H → 15M workflow", "EOD fade after sweep", "Professional checklist"],
    commonMistakes: ["Skipping workflow steps", "Execution before context"],
    journalPrompt: "Walk through your full EOD workflow.",
    reversalGrade: "A",
  },
  {
    id: "pack-eod-13-choch-eod",
    title: "CHOCH at Session Close",
    description: "Change of character prints as session closes.",
    symbol: "GBPUSD",
    kind: "uptrend-reversal",
    seed: "pack-eod-13",
    category: "reversal",
    difficulty: "Advanced",
    correctTrend: "downtrend",
    bestStrategy: "reversal",
    strategyOptions: [...EOD_OPTS],
    idealDirection: "sell",
    behaviour: "reversal",
    subcategory: "choch",
    tags: ["eod", "choch", "advanced"],
    session: "New York Close",
    hints: ["CHOCH = first sign of reversal", "EOD CHOCH sets next session bias", "Confirm with LL"],
    commonMistakes: ["Confusing CHOCH with pullback", "Acting on one candle"],
    journalPrompt: "How is EOD CHOCH different from intraday noise?",
    reversalGrade: "A",
  },
  {
    id: "pack-eod-14-institutional-rev",
    title: "Institutional EOD Reversal",
    description: "Institutional fade at session extreme with HTF confluence.",
    symbol: "EURUSD",
    kind: "fakeout",
    seed: "pack-eod-14",
    category: "reversal",
    difficulty: "Advanced",
    correctTrend: "downtrend",
    bestStrategy: "liquidity-sweep",
    strategyOptions: [...EOD_OPTS],
    idealDirection: "sell",
    behaviour: "reversal",
    subcategory: "institutional-reversal",
    tags: ["eod", "institutional", "advanced"],
    session: "New York Close",
    hints: ["Institutions fade retail at EOD", "Liquidity + HTF = A+ reversal", "Size for volatility"],
    commonMistakes: ["Retail breakout buying at EOD", "No HTF confluence check"],
    journalPrompt: "What institutional behaviour did you recognise?",
    reversalGrade: "A+",
  },
  {
    id: "pack-eod-15-weak-eod-cont",
    title: "Weak EOD — No Continuation",
    description: "Daily continuation failing into close. Stand aside?",
    symbol: "USDJPY",
    kind: "uptrend",
    seed: "pack-eod-15",
    category: "continuation",
    difficulty: "Advanced",
    correctTrend: "uptrend",
    bestStrategy: "no-trade",
    strategyOptions: [...EOD_OPTS],
    idealDirection: "no-trade",
    behaviour: "continuation",
    subcategory: "failing-continuation",
    tags: ["eod", "no-trade", "advanced"],
    session: "New York Close",
    hints: ["Failing momentum into close", "No trade when daily weakens", "Preserve capital"],
    commonMistakes: ["Forcing EOD continuation", "Ignoring momentum loss"],
    journalPrompt: "When does EOD continuation become invalid?",
  },
  {
    id: "pack-eod-16-daily-alignment",
    title: "Daily + Intraday Alignment",
    description: "Daily and intraday both bullish into close. High-conviction continuation?",
    symbol: "EURUSD",
    kind: "uptrend",
    seed: "pack-eod-16",
    category: "continuation",
    difficulty: "Professional",
    correctTrend: "uptrend",
    bestStrategy: "continuation",
    strategyOptions: [...EOD_OPTS],
    idealDirection: "buy",
    behaviour: "continuation",
    subcategory: "htf-alignment",
    tags: ["eod", "htf-alignment", "professional"],
    session: "New York Close",
    hints: ["Alignment = highest probability", "Daily and 15M same direction", "Still size down at EOD"],
    commonMistakes: ["Oversizing on alignment", "No EOD exit plan"],
    journalPrompt: "How does HTF alignment change conviction?",
    reversalGrade: "A",
  },
  {
    id: "pack-eod-17-close-reversal-pro",
    title: "Professional Close Reversal",
    description: "Textbook EOD reversal — sweep, rejection, HTF confluence.",
    symbol: "XAUUSD",
    kind: "downtrend-reversal",
    seed: "pack-eod-17",
    category: "reversal",
    difficulty: "Professional",
    correctTrend: "uptrend",
    bestStrategy: "reversal",
    strategyOptions: [...EOD_OPTS],
    idealDirection: "buy",
    behaviour: "reversal",
    subcategory: "close-reversal-pro",
    tags: ["eod", "professional", "reversal"],
    session: "New York Close",
    hints: ["This is the EOD reversal playbook", "Sweep → reject → enter", "Gold needs wider stops"],
    commonMistakes: ["Entering before sweep completes", "Tight stops on gold EOD"],
    journalPrompt: "Full EOD reversal workflow review.",
    reversalGrade: "A+",
  },
  {
    id: "pack-eod-18-session-handoff",
    title: "Session Handoff Trap",
    description: "Asia/London handoff creates false EOD signal.",
    symbol: "GBPUSD",
    kind: "fakeout",
    seed: "pack-eod-18",
    category: "fakeout",
    difficulty: "Professional",
    correctTrend: "range",
    bestStrategy: "no-trade",
    strategyOptions: [...EOD_OPTS],
    idealDirection: "wait",
    behaviour: "range",
    subcategory: "session-handoff",
    tags: ["eod", "session-handoff", "professional"],
    session: "Asian",
    hints: ["Session handoffs create false signals", "Wait for new session structure", "Patience at transitions"],
    commonMistakes: ["Trading session transition noise", "Confusing handoff with EOD reversal"],
    journalPrompt: "How do session handoffs differ from EOD reversals?",
  },
  {
    id: "pack-eod-19-master-context",
    title: "Master Daily Context",
    description: "Everything depends on daily read. Execute only with alignment.",
    symbol: "EURUSD",
    kind: "uptrend",
    seed: "pack-eod-19",
    category: "continuation",
    difficulty: "Professional",
    correctTrend: "uptrend",
    bestStrategy: "continuation",
    strategyOptions: [...EOD_OPTS],
    idealDirection: "buy",
    behaviour: "continuation",
    subcategory: "master-context",
    tags: ["eod", "daily-context", "professional", "master"],
    session: "New York Close",
    hints: ["Daily context is non-negotiable", "Execution is the last step", "A+ EOD setup"],
    commonMistakes: ["Skipping to execution", "Ignoring daily resistance ahead"],
    journalPrompt: "Master workflow — daily context to execution.",
    reversalGrade: "A+",
  },
  {
    id: "pack-eod-20-eod-mastery",
    title: "EOD Mastery Challenge",
    description: "Full professional EOD assessment — context, behaviour, execution.",
    symbol: "EURUSD",
    kind: "downtrend-reversal",
    seed: "pack-eod-20",
    category: "reversal",
    difficulty: "Professional",
    correctTrend: "uptrend",
    bestStrategy: "reversal",
    strategyOptions: [...EOD_OPTS],
    idealDirection: "buy",
    behaviour: "reversal",
    subcategory: "eod-mastery",
    tags: ["eod", "mastery", "professional", "assessment"],
    session: "New York Close",
    hints: ["Read daily first", "Identify session phase", "Execute only with confluence", "Grade your process"],
    commonMistakes: ["Rushing EOD decisions", "No process checklist"],
    journalPrompt: "Complete EOD mastery self-assessment.",
    reversalGrade: "A+",
  },
]

export const EOD_ACADEMY_SCENARIOS = buildPackFromDefs("eod", DEFS)
