import { buildPackFromDefs, type PackScenarioDef } from "./types"

const SKIP_OPTS = ["continuation", "reversal", "range", "no-trade"] as const

const DEFS: PackScenarioDef[] = [
  {
    id: "pack-pat-01-range-no-edge",
    title: "Range — No Edge",
    description: "Overlapping highs and lows. Is there a trade here?",
    symbol: "EURUSD",
    kind: "ranging",
    seed: "pack-pat-01",
    category: "range",
    difficulty: "Beginner",
    correctTrend: "range",
    bestStrategy: "no-trade",
    strategyOptions: [...SKIP_OPTS],
    idealDirection: "no-trade",
    behaviour: "range",
    subcategory: "no-edge",
    tags: ["range", "no-trade", "patience", "beginner"],
    session: "Asian",
    hints: ["No HH/HL or LH/LL sequence", "Standing aside is professional", "Wait for expansion"],
    commonMistakes: ["Forcing trades in range", "Overtrading low ATR"],
    journalPrompt: "Why was no trade the highest-probability decision?",
  },
  {
    id: "pack-pat-02-session-chop",
    title: "Session Chop",
    description: "Whipsaw between levels with no follow-through.",
    symbol: "GBPUSD",
    kind: "ranging",
    seed: "pack-pat-02",
    category: "range",
    difficulty: "Beginner",
    correctTrend: "range",
    bestStrategy: "no-trade",
    strategyOptions: [...SKIP_OPTS],
    idealDirection: "wait",
    behaviour: "range",
    subcategory: "chop",
    tags: ["chop", "no-trade", "patience", "beginner"],
    session: "London",
    hints: ["Chop punishes overtrading", "No clear structure", "Patience preserves capital"],
    commonMistakes: ["Revenge trading after whipsaw", "Increasing size to recover"],
    journalPrompt: "How does chop erode edge over time?",
  },
  {
    id: "pack-pat-03-fake-breakout",
    title: "Fake Breakout — Stand Aside",
    description: "Breakout fails immediately. Trade the fake or wait?",
    symbol: "EURUSD",
    kind: "fakeout",
    seed: "pack-pat-03",
    category: "fakeout",
    difficulty: "Beginner",
    correctTrend: "range",
    bestStrategy: "no-trade",
    strategyOptions: ["liquidity-sweep", "reversal", "no-trade", "continuation"],
    idealDirection: "wait",
    behaviour: "range",
    subcategory: "fake-breakout",
    tags: ["fakeout", "patience", "beginner"],
    session: "London",
    hints: ["False breaks trap breakout traders", "Wait for confirmation", "No trade until clarity"],
    commonMistakes: ["Buying the breakout", "Fading without confirmation"],
    journalPrompt: "Why is patience correct on ambiguous fakeouts?",
  },
  {
    id: "pack-pat-04-weak-structure",
    title: "Weak Structure — No Trade",
    description: "Messy swings with no clean sequence. Trade or skip?",
    symbol: "EURUSD",
    kind: "ranging",
    seed: "pack-pat-04",
    category: "range",
    difficulty: "Beginner",
    correctTrend: "range",
    bestStrategy: "no-trade",
    strategyOptions: [...SKIP_OPTS],
    idealDirection: "no-trade",
    behaviour: "range",
    subcategory: "weak-structure",
    tags: ["weak-structure", "no-trade", "beginner"],
    session: "Asian",
    hints: ["Weak structure = low probability", "Professionals skip unclear charts", "Clarity is an edge"],
    commonMistakes: ["Trading messy charts", "Forcing a narrative"],
    journalPrompt: "What made structure too weak to trade?",
  },
  {
    id: "pack-pat-05-no-confirmation",
    title: "No Confirmation Candle",
    description: "Setup forming but no confirmation yet. Enter or wait?",
    symbol: "GBPUSD",
    kind: "uptrend",
    seed: "pack-pat-05",
    category: "continuation",
    difficulty: "Beginner",
    correctTrend: "uptrend",
    bestStrategy: "no-trade",
    strategyOptions: [...SKIP_OPTS],
    idealDirection: "wait",
    behaviour: "continuation",
    subcategory: "no-confirmation",
    tags: ["patience", "confirmation", "beginner"],
    session: "London",
    hints: ["No confirmation = no trade", "Wait for the candle to close", "Anticipation is not edge"],
    commonMistakes: ["Entering before confirmation", "Guessing the next candle"],
    journalPrompt: "Why must confirmation close before entry?",
  },
  {
    id: "pack-pat-06-poor-rr",
    title: "Poor Risk/Reward",
    description: "Valid direction but R:R below 1:1.5. Take it anyway?",
    symbol: "EURUSD",
    kind: "uptrend",
    seed: "pack-pat-06",
    category: "continuation",
    difficulty: "Intermediate",
    correctTrend: "uptrend",
    bestStrategy: "no-trade",
    strategyOptions: [...SKIP_OPTS],
    idealDirection: "no-trade",
    behaviour: "continuation",
    subcategory: "poor-rr",
    tags: ["risk-reward", "no-trade", "intermediate"],
    session: "New York",
    hints: ["Poor R:R destroys long-term edge", "Skip sub-1.5 setups", "Wait for better entry"],
    commonMistakes: ["Taking trades for action", "Ignoring R:R math"],
    journalPrompt: "How does poor R:R compound into losses?",
  },
  {
    id: "pack-pat-07-late-entry",
    title: "Late Entry — Missed It",
    description: "Move already extended. Chase or stand aside?",
    symbol: "GBPUSD",
    kind: "uptrend",
    seed: "pack-pat-07",
    category: "continuation",
    difficulty: "Intermediate",
    correctTrend: "uptrend",
    bestStrategy: "no-trade",
    strategyOptions: [...SKIP_OPTS],
    idealDirection: "no-trade",
    behaviour: "continuation",
    subcategory: "late-entry",
    tags: ["late-entry", "no-trade", "intermediate"],
    session: "New York",
    hints: ["Late entries have poor R:R", "Missed trade ≠ must chase", "Next setup will come"],
    commonMistakes: ["FOMO chasing", "Revenge entering extended moves"],
    journalPrompt: "Why is missing a trade better than chasing?",
  },
  {
    id: "pack-pat-08-low-probability",
    title: "Low Probability Setup",
    description: "Multiple factors conflict. Edge is thin.",
    symbol: "USDJPY",
    kind: "downtrend-reversal",
    seed: "pack-pat-08",
    category: "reversal",
    difficulty: "Intermediate",
    correctTrend: "range",
    bestStrategy: "no-trade",
    strategyOptions: [...SKIP_OPTS],
    idealDirection: "wait",
    behaviour: "reversal",
    subcategory: "low-probability",
    tags: ["low-probability", "patience", "intermediate"],
    session: "London",
    hints: ["Conflicting signals = no trade", "Edge requires alignment", "Professionals pass on coin flips"],
    commonMistakes: ["Trading 50/50 setups", "Needing to be in the market"],
    journalPrompt: "What factors conflicted and killed the edge?",
  },
  {
    id: "pack-pat-09-htf-conflict",
    title: "HTF Conflict — Wait",
    description: "Lower TF setup fights higher timeframe bias.",
    symbol: "EURUSD",
    kind: "downtrend",
    seed: "pack-pat-09",
    category: "reversal",
    difficulty: "Intermediate",
    correctTrend: "downtrend",
    bestStrategy: "no-trade",
    strategyOptions: [...SKIP_OPTS],
    idealDirection: "no-trade",
    behaviour: "reversal",
    subcategory: "htf-conflict",
    tags: ["htf-conflict", "no-trade", "intermediate"],
    session: "London",
    hints: ["HTF bias wins over LTF noise", "Don't counter HTF without strong reason", "Context first"],
    commonMistakes: ["Ignoring daily bias", "LTF tunnel vision"],
    journalPrompt: "How did HTF conflict invalidate the LTF setup?",
  },
  {
    id: "pack-pat-10-news-spike",
    title: "News Spike Chaos",
    description: "Violent spike with no structure. Trade the chaos?",
    symbol: "GBPUSD",
    kind: "fakeout",
    seed: "pack-pat-10",
    category: "fakeout",
    difficulty: "Intermediate",
    correctTrend: "range",
    bestStrategy: "no-trade",
    strategyOptions: [...SKIP_OPTS, "liquidity-sweep"],
    idealDirection: "no-trade",
    behaviour: "range",
    subcategory: "news-spike",
    tags: ["news", "no-trade", "patience", "intermediate"],
    session: "New York",
    hints: ["News spikes are untradeable for most", "Spread widens — edge disappears", "Wait for structure to return"],
    commonMistakes: ["Trading news spikes", "Widened spread entries"],
    journalPrompt: "Why do professionals avoid news chaos?",
  },
  {
    id: "pack-pat-11-mid-range",
    title: "Mid-Range Entry Trap",
    description: "Price in middle of range — worst place to enter.",
    symbol: "EURUSD",
    kind: "ranging",
    seed: "pack-pat-11",
    category: "range",
    difficulty: "Advanced",
    correctTrend: "range",
    bestStrategy: "no-trade",
    strategyOptions: [...SKIP_OPTS],
    idealDirection: "no-trade",
    behaviour: "range",
    subcategory: "mid-range",
    tags: ["range", "no-trade", "advanced"],
    session: "Asian",
    hints: ["Mid-range = no man's land", "Wait for range edges", "Poor R:R in the middle"],
    commonMistakes: ["Entering mid-range", "No defined stop level"],
    journalPrompt: "Why is mid-range the worst entry zone?",
  },
  {
    id: "pack-pat-12-exhaustion-wait",
    title: "Exhaustion — Don't Fade Yet",
    description: "Extended move but no reversal confirmation. Fade or wait?",
    symbol: "XAUUSD",
    kind: "uptrend",
    seed: "pack-pat-12",
    category: "reversal",
    difficulty: "Advanced",
    correctTrend: "uptrend",
    bestStrategy: "no-trade",
    strategyOptions: ["reversal", "continuation", "no-trade"],
    idealDirection: "wait",
    behaviour: "reversal",
    subcategory: "premature-fade",
    tags: ["exhaustion", "patience", "advanced"],
    session: "New York",
    hints: ["Exhaustion alone isn't a signal", "Need structure break to fade", "Trend can extend further"],
    commonMistakes: ["Fading without BOS", "Top picking in trends"],
    journalPrompt: "What's missing before a valid reversal fade?",
  },
  {
    id: "pack-pat-13-spread-wide",
    title: "Wide Spread Conditions",
    description: "Setup exists but spread eats the edge.",
    symbol: "GBPUSD",
    kind: "ranging",
    seed: "pack-pat-13",
    category: "range",
    difficulty: "Advanced",
    correctTrend: "range",
    bestStrategy: "no-trade",
    strategyOptions: [...SKIP_OPTS],
    idealDirection: "no-trade",
    behaviour: "range",
    subcategory: "spread-conditions",
    tags: ["spread", "no-trade", "advanced"],
    session: "Asian",
    hints: ["Spread is a real cost", "Thin Asian session reduces edge", "Wait for liquid sessions"],
    commonMistakes: ["Ignoring spread in R:R", "Trading illiquid hours"],
    journalPrompt: "How does spread change your minimum R:R?",
  },
  {
    id: "pack-pat-14-double-fake",
    title: "Double Fake Breakout",
    description: "Two failed breakouts — maximum confusion.",
    symbol: "EURUSD",
    kind: "fakeout",
    seed: "pack-pat-14",
    category: "fakeout",
    difficulty: "Advanced",
    correctTrend: "range",
    bestStrategy: "no-trade",
    strategyOptions: [...SKIP_OPTS],
    idealDirection: "no-trade",
    behaviour: "range",
    subcategory: "double-fake",
    tags: ["fakeout", "patience", "advanced"],
    session: "London",
    hints: ["Double fakes = stay flat", "Market is undecided", "Capital preservation mode"],
    commonMistakes: ["Trading the third breakout blindly", "Frustration trading"],
    journalPrompt: "When does confusion signal no trade?",
  },
  {
    id: "pack-pat-15-counter-trend-trap",
    title: "Counter-Trend Trap",
    description: "Tempting counter-trend setup with no HTF support.",
    symbol: "USDJPY",
    kind: "downtrend",
    seed: "pack-pat-15",
    category: "reversal",
    difficulty: "Advanced",
    correctTrend: "downtrend",
    bestStrategy: "no-trade",
    strategyOptions: [...SKIP_OPTS],
    idealDirection: "no-trade",
    behaviour: "reversal",
    subcategory: "counter-trend-trap",
    tags: ["counter-trend", "no-trade", "advanced"],
    session: "New York",
    hints: ["Counter-trend needs strong confirmation", "Fighting trend is low probability", "Wait for alignment"],
    commonMistakes: ["Catching falling knives", "Ignoring dominant trend"],
    journalPrompt: "Why was counter-trend unjustified here?",
  },
  {
    id: "pack-pat-16-overlap-structure",
    title: "Overlapping Structure",
    description: "Equal highs and lows — no directional bias.",
    symbol: "EURUSD",
    kind: "ranging",
    seed: "pack-pat-16",
    category: "range",
    difficulty: "Professional",
    correctTrend: "range",
    bestStrategy: "no-trade",
    strategyOptions: [...SKIP_OPTS],
    idealDirection: "no-trade",
    behaviour: "range",
    subcategory: "overlap",
    tags: ["overlap", "no-trade", "professional"],
    session: "London",
    hints: ["Overlap = equilibrium", "Institutions accumulate here — retail loses", "Wait for imbalance"],
    commonMistakes: ["Directional bias in balance", "Overtrading equilibrium"],
    journalPrompt: "How do professionals trade overlap differently from retail?",
  },
  {
    id: "pack-pat-17-ambiguous-break",
    title: "Ambiguous Structure Break",
    description: "Possible BOS but not confirmed across timeframes.",
    symbol: "GBPUSD",
    kind: "uptrend-reversal",
    seed: "pack-pat-17",
    category: "reversal",
    difficulty: "Professional",
    correctTrend: "range",
    bestStrategy: "no-trade",
    strategyOptions: [...SKIP_OPTS],
    idealDirection: "wait",
    behaviour: "reversal",
    subcategory: "ambiguous-bos",
    tags: ["bos", "patience", "professional"],
    session: "New York",
    hints: ["Ambiguous BOS = wait", "Need LH + LL for bearish", "One swing break isn't enough"],
    commonMistakes: ["Calling BOS on one candle", "Acting on ambiguity"],
    journalPrompt: "What confirmation was still missing?",
    reversalGrade: "C",
  },
  {
    id: "pack-pat-18-revenge-setup",
    title: "Emotional Re-Entry Trap",
    description: "Previous loss nearby — tempting re-entry without edge.",
    symbol: "EURUSD",
    kind: "ranging",
    seed: "pack-pat-18",
    category: "range",
    difficulty: "Professional",
    correctTrend: "range",
    bestStrategy: "no-trade",
    strategyOptions: [...SKIP_OPTS],
    idealDirection: "no-trade",
    behaviour: "range",
    subcategory: "emotional-trap",
    tags: ["psychology", "no-trade", "professional"],
    session: "London",
    hints: ["Revenge trading destroys accounts", "No edge = no trade regardless of emotion", "Step away if tilted"],
    commonMistakes: ["Revenge trading", "Increasing size after loss"],
    journalPrompt: "How do you recognise emotional re-entry?",
  },
  {
    id: "pack-pat-19-institutional-wait",
    title: "Institutional Patience",
    description: "Textbook example of when institutions stay flat.",
    symbol: "XAUUSD",
    kind: "ranging",
    seed: "pack-pat-19",
    category: "range",
    difficulty: "Professional",
    correctTrend: "range",
    bestStrategy: "no-trade",
    strategyOptions: [...SKIP_OPTS],
    idealDirection: "no-trade",
    behaviour: "range",
    subcategory: "institutional-wait",
    tags: ["institutional", "no-trade", "professional"],
    session: "New York Close",
    hints: ["Institutions wait for A+ setups", "Flat is a position", "Excellent patience is a skill"],
    commonMistakes: ["Needing to trade daily", "Confusing activity with productivity"],
    journalPrompt: "Why is staying flat the professional move?",
    reversalGrade: "A+",
  },
  {
    id: "pack-pat-20-master-discipline",
    title: "Master Discipline — No Trade",
    description: "Everything says wait. The master move is no trade.",
    symbol: "EURUSD",
    kind: "ranging",
    seed: "pack-pat-20",
    category: "range",
    difficulty: "Professional",
    correctTrend: "range",
    bestStrategy: "no-trade",
    strategyOptions: [...SKIP_OPTS],
    idealDirection: "no-trade",
    behaviour: "range",
    subcategory: "master-discipline",
    tags: ["discipline", "no-trade", "professional", "master"],
    session: "Asian",
    hints: ["This is an A+ no-trade scenario", "Recognising no edge is mastery", "Protect capital for A+ setups"],
    commonMistakes: ["Trading out of boredom", "Undervaluing patience as a skill"],
    journalPrompt: "Full workflow — why is this master-level patience?",
    reversalGrade: "A+",
  },
]

export const PATIENCE_ACADEMY_SCENARIOS = buildPackFromDefs("patience", DEFS)
