import type { ScenarioMeta } from "./scenarios"
import { buildExecutionScenario } from "./scenarios"
import type { ExecutionScenario } from "@/lib/execution-lab/types"

const REVERSAL_PACK: ScenarioMeta[] = [
  {
    id: "rev-eur-healthy-cont",
    title: "Healthy Continuation",
    description: "Uptrend pullback — structure intact. Continuation or trap?",
    symbol: "EURUSD",
    kind: "uptrend",
    seed: "rev-eur-hc-01",
    category: "continuation",
    behaviour: "continuation",
    subcategory: "pullback",
    tags: ["continuation", "eurusd", "beginner"],
    difficulty: "Beginner",
    correctTrend: "uptrend",
    bestStrategy: "continuation",
    strategyOptions: ["continuation", "reversal", "range", "no-trade"],
    idealDirection: "buy",
    pipSize: 0.0001,
    pipValuePerLot: 10,
    defaultAccount: 10000,
    pauseFraction: 0.72,
    hints: ["HH/HL still intact", "Pullback, not reversal"],
    journalPrompt: "Why was this continuation, not reversal?",
    reversalGrade: "B",
  },
  {
    id: "rev-gbp-false-rev",
    title: "False Reversal Signal",
    description: "One lower high appears — is the trend over?",
    symbol: "GBPUSD",
    kind: "uptrend",
    seed: "rev-gbp-fr-02",
    category: "fakeout",
    behaviour: "fakeout",
    subcategory: "false-reversal",
    tags: ["reversal", "fakeout", "intermediate"],
    difficulty: "Intermediate",
    correctTrend: "uptrend",
    bestStrategy: "continuation",
    strategyOptions: ["continuation", "reversal", "no-trade"],
    idealDirection: "wait",
    pipSize: 0.0001,
    pipValuePerLot: 10,
    defaultAccount: 10000,
    pauseFraction: 0.74,
    hints: ["One swing break is not confirmation", "Wait for LL after LH"],
    journalPrompt: "What confirmed this was a trap?",
    reversalGrade: "C",
  },
  {
    id: "rev-eur-strong-rev",
    title: "Strong Bearish Reversal",
    description: "Uptrend breaks with LH and LL — trade the reversal?",
    symbol: "EURUSD",
    kind: "uptrend-reversal",
    seed: "rev-eur-sr-03",
    category: "reversal",
    behaviour: "reversal",
    subcategory: "structure-break",
    tags: ["reversal", "bos", "intermediate"],
    difficulty: "Intermediate",
    correctTrend: "downtrend",
    bestStrategy: "reversal",
    strategyOptions: ["reversal", "continuation", "no-trade"],
    idealDirection: "sell",
    pipSize: 0.0001,
    pipValuePerLot: 10,
    defaultAccount: 10000,
    pauseFraction: 0.76,
    hints: ["LH then LL confirms", "Retest adds confluence"],
    journalPrompt: "Where was structure invalidation?",
    reversalGrade: "A",
  },
  {
    id: "rev-xau-london-rev",
    title: "Gold London Reversal",
    description: "XAUUSD rejects session high — reversal or pullback?",
    symbol: "XAUUSD",
    kind: "downtrend-reversal",
    seed: "rev-xau-lon-04",
    category: "reversal",
    behaviour: "reversal",
    subcategory: "london-reversal",
    tags: ["reversal", "gold", "london", "advanced"],
    difficulty: "Advanced",
    correctTrend: "uptrend",
    bestStrategy: "reversal",
    strategyOptions: ["reversal", "continuation", "liquidity-sweep", "no-trade"],
    idealDirection: "buy",
    pipSize: 0.01,
    pipValuePerLot: 1,
    defaultAccount: 10000,
    pauseFraction: 0.73,
    hints: ["Session liquidity often sweeps first", "Confirm on 4H"],
    journalPrompt: "Did London session context support this?",
    reversalGrade: "A",
  },
  {
    id: "rev-jpy-ny-rev",
    title: "USDJPY New York Reversal",
    description: "NY session prints exhaustion after London impulse.",
    symbol: "USDJPY",
    kind: "downtrend",
    seed: "rev-jpy-ny-05",
    category: "reversal",
    behaviour: "reversal",
    subcategory: "new-york-reversal",
    tags: ["reversal", "usdjpy", "new-york"],
    difficulty: "Advanced",
    correctTrend: "downtrend",
    bestStrategy: "reversal",
    strategyOptions: ["reversal", "continuation", "no-trade"],
    idealDirection: "sell",
    pipSize: 0.01,
    pipValuePerLot: 9,
    defaultAccount: 10000,
    pauseFraction: 0.75,
    hints: ["Momentum fading into NY", "Look for LH/LL"],
    journalPrompt: "Session timing matters",
    reversalGrade: "B",
  },
  {
    id: "rev-eur-weak-rev",
    title: "Weak Counter-Trend Reversal",
    description: "Tiny structure break against strong daily trend.",
    symbol: "EURUSD",
    kind: "uptrend-reversal",
    seed: "rev-eur-wk-06",
    category: "reversal",
    behaviour: "reversal",
    subcategory: "weak-reversal",
    tags: ["reversal", "counter-trend"],
    difficulty: "Intermediate",
    correctTrend: "uptrend",
    bestStrategy: "no-trade",
    strategyOptions: ["reversal", "continuation", "no-trade"],
    idealDirection: "no-trade",
    pipSize: 0.0001,
    pipValuePerLot: 10,
    defaultAccount: 10000,
    pauseFraction: 0.7,
    hints: ["HTF trend still bullish", "Low quality reversal — skip"],
    journalPrompt: "Why skip weak counter-trend reversals?",
    reversalGrade: "D",
  },
  {
    id: "rev-gbp-liq-sweep",
    title: "Liquidity Sweep Reversal",
    description: "Sweep above highs then aggressive sell-off.",
    symbol: "GBPUSD",
    kind: "fakeout",
    seed: "rev-gbp-ls-07",
    category: "liquidity",
    behaviour: "liquidity-sweep",
    subcategory: "liquidity-sweep",
    tags: ["liquidity", "reversal", "gbpusd"],
    difficulty: "Advanced",
    correctTrend: "downtrend",
    bestStrategy: "liquidity-sweep",
    strategyOptions: ["liquidity-sweep", "reversal", "continuation", "no-trade"],
    idealDirection: "sell",
    pipSize: 0.0001,
    pipValuePerLot: 10,
    defaultAccount: 10000,
    pauseFraction: 0.78,
    hints: ["Stops sit above the sweep", "Enter after rejection"],
    journalPrompt: "Where was liquidity taken?",
    reversalGrade: "A+",
  },
  {
    id: "rev-eur-eod-cont",
    title: "EOD Continuation",
    description: "End of day — trend resumes into the close.",
    symbol: "EURUSD",
    kind: "uptrend",
    seed: "rev-eur-eodc-08",
    category: "continuation",
    behaviour: "eod-continuation",
    subcategory: "eod-continuation",
    tags: ["eod", "continuation", "eurusd"],
    difficulty: "Advanced",
    correctTrend: "uptrend",
    bestStrategy: "continuation",
    strategyOptions: ["continuation", "reversal", "no-trade"],
    idealDirection: "buy",
    pipSize: 0.0001,
    pipValuePerLot: 10,
    defaultAccount: 10000,
    pauseFraction: 0.8,
    timeframe: "1H",
    hints: ["Daily bias bullish", "EOD continuation with trend"],
    journalPrompt: "How did daily bias guide this?",
    reversalGrade: "A",
  },
  {
    id: "rev-eur-eod-rev",
    title: "EOD Reversal",
    description: "Daily exhaustion — reversal into the close.",
    symbol: "EURUSD",
    kind: "uptrend-reversal",
    seed: "rev-eur-eodr-09",
    category: "reversal",
    behaviour: "eod-reversal",
    subcategory: "eod-reversal",
    tags: ["eod", "reversal", "eurusd"],
    difficulty: "Professional",
    correctTrend: "downtrend",
    bestStrategy: "reversal",
    strategyOptions: ["reversal", "continuation", "no-trade"],
    idealDirection: "sell",
    pipSize: 0.0001,
    pipValuePerLot: 10,
    defaultAccount: 10000,
    pauseFraction: 0.82,
    timeframe: "1H",
    hints: ["Exhaustion at HTF resistance", "Confirm structure break"],
    journalPrompt: "Walk through the EOD checklist.",
    reversalGrade: "A+",
  },
  {
    id: "rev-xau-no-trade",
    title: "Gold — No Trade",
    description: "Messy structure after news — stand aside.",
    symbol: "XAUUSD",
    kind: "ranging",
    seed: "rev-xau-nt-10",
    category: "range",
    behaviour: "no-trade",
    subcategory: "post-news",
    tags: ["no-trade", "gold", "range"],
    difficulty: "Intermediate",
    correctTrend: "range",
    bestStrategy: "no-trade",
    strategyOptions: ["continuation", "reversal", "range", "no-trade"],
    idealDirection: "no-trade",
    pipSize: 0.01,
    pipValuePerLot: 1,
    defaultAccount: 10000,
    pauseFraction: 0.68,
    hints: ["No clear behaviour", "Patience is the edge"],
    journalPrompt: "Why was no trade correct?",
    reversalGrade: "B",
  },
  {
    id: "rev-eur-pullback-deep",
    title: "Deep Pullback",
    description: "Pullback looks scary — but structure holds.",
    symbol: "EURUSD",
    kind: "uptrend",
    seed: "rev-eur-dp-11",
    category: "continuation",
    behaviour: "pullback",
    subcategory: "deep-pullback",
    tags: ["pullback", "continuation"],
    difficulty: "Intermediate",
    correctTrend: "uptrend",
    bestStrategy: "continuation",
    strategyOptions: ["continuation", "reversal", "no-trade"],
    idealDirection: "buy",
    pipSize: 0.0001,
    pipValuePerLot: 10,
    defaultAccount: 10000,
    pauseFraction: 0.71,
    hints: ["HL still holds", "Deep ≠ reversal"],
    journalPrompt: "How to tell deep pullback from reversal?",
    reversalGrade: "B",
  },
  {
    id: "rev-gbp-rev-confirm",
    title: "Confirmed GBP Reversal",
    description: "LH, LL, retest — full reversal sequence.",
    symbol: "GBPUSD",
    kind: "downtrend-reversal",
    seed: "rev-gbp-cr-12",
    category: "reversal",
    behaviour: "reversal",
    tags: ["reversal", "gbpusd", "retest"],
    difficulty: "Intermediate",
    correctTrend: "uptrend",
    bestStrategy: "reversal",
    strategyOptions: ["reversal", "break-retest", "no-trade"],
    idealDirection: "buy",
    pipSize: 0.0001,
    pipValuePerLot: 10,
    defaultAccount: 10000,
    pauseFraction: 0.77,
    hints: ["Four point rule complete", "Retest confirms"],
    journalPrompt: "Map the four structural points.",
    reversalGrade: "A",
  },
  {
    id: "rev-jpy-cont-trap",
    title: "Continuation Trap",
    description: "Looks like reversal — explodes higher.",
    symbol: "USDJPY",
    kind: "uptrend",
    seed: "rev-jpy-ct-13",
    category: "continuation",
    behaviour: "continuation-trap",
    tags: ["continuation", "trap", "usdjpy"],
    difficulty: "Advanced",
    correctTrend: "uptrend",
    bestStrategy: "continuation",
    strategyOptions: ["continuation", "reversal", "no-trade"],
    idealDirection: "wait",
    pipSize: 0.01,
    pipValuePerLot: 9,
    defaultAccount: 10000,
    pauseFraction: 0.73,
    hints: ["Structure not broken", "Don't short early"],
    journalPrompt: "What looked like reversal but wasn't?",
    reversalGrade: "C",
  },
  {
    id: "rev-eur-falling-knife",
    title: "Falling Knife",
    description: "Price dropping — should you buy?",
    symbol: "EURUSD",
    kind: "downtrend",
    seed: "rev-eur-fk-14",
    category: "reversal",
    behaviour: "reversal",
    subcategory: "falling-knife",
    tags: ["reversal", "psychology"],
    difficulty: "Beginner",
    correctTrend: "downtrend",
    bestStrategy: "no-trade",
    strategyOptions: ["reversal", "continuation", "no-trade"],
    idealDirection: "no-trade",
    pipSize: 0.0001,
    pipValuePerLot: 10,
    defaultAccount: 10000,
    pauseFraction: 0.65,
    hints: ["Cheap price ≠ buy signal", "Wait for structure change"],
    journalPrompt: "Why not catch falling knives?",
    reversalGrade: "D",
  },
  {
    id: "rev-xau-inst-rev",
    title: "Institutional Gold Reversal",
    description: "HTF resistance + liquidity sweep + BOS.",
    symbol: "XAUUSD",
    kind: "fakeout",
    seed: "rev-xau-in-15",
    category: "reversal",
    behaviour: "reversal",
    subcategory: "institutional",
    tags: ["reversal", "gold", "liquidity", "htf"],
    difficulty: "Professional",
    correctTrend: "downtrend",
    bestStrategy: "liquidity-sweep",
    strategyOptions: ["liquidity-sweep", "reversal", "no-trade"],
    idealDirection: "sell",
    pipSize: 0.01,
    pipValuePerLot: 1,
    defaultAccount: 10000,
    pauseFraction: 0.79,
    hints: ["HTF level + sweep", "A+ institutional setup"],
    journalPrompt: "List all confluence factors.",
    reversalGrade: "A+",
  },
  {
    id: "rev-eur-range-fake",
    title: "Range Fake Breakout",
    description: "Breakout fails back into range.",
    symbol: "EURUSD",
    kind: "ranging",
    seed: "rev-eur-rf-16",
    category: "fakeout",
    behaviour: "fakeout",
    tags: ["range", "fakeout"],
    difficulty: "Intermediate",
    correctTrend: "range",
    bestStrategy: "no-trade",
    strategyOptions: ["reversal", "range", "no-trade"],
    idealDirection: "no-trade",
    pipSize: 0.0001,
    pipValuePerLot: 10,
    defaultAccount: 10000,
    pauseFraction: 0.7,
    hints: ["Failed breakout = range continues", "Wait for clean break"],
    journalPrompt: "Why fake breakouts happen in ranges.",
    reversalGrade: "C",
  },
  {
    id: "rev-gbp-eod-rev",
    title: "GBP EOD Reversal",
    description: "Sterling exhausts into daily close.",
    symbol: "GBPUSD",
    kind: "uptrend-reversal",
    seed: "rev-gbp-eod-17",
    category: "reversal",
    behaviour: "eod-reversal",
    tags: ["eod", "gbpusd", "reversal"],
    difficulty: "Professional",
    correctTrend: "downtrend",
    bestStrategy: "reversal",
    strategyOptions: ["reversal", "continuation", "no-trade"],
    idealDirection: "sell",
    pipSize: 0.0001,
    pipValuePerLot: 10,
    defaultAccount: 10000,
    pauseFraction: 0.81,
    timeframe: "1H",
    hints: ["Daily exhaustion wick", "4H structure break"],
    journalPrompt: "EOD reversal checklist review.",
    reversalGrade: "A",
  },
  {
    id: "rev-eur-momentum-bounce",
    title: "Momentum Bounce (Not Reversal)",
    description: "Sharp bounce in downtrend — trap for buyers?",
    symbol: "EURUSD",
    kind: "downtrend",
    seed: "rev-eur-mb-18",
    category: "continuation",
    behaviour: "pullback",
    tags: ["pullback", "downtrend"],
    difficulty: "Intermediate",
    correctTrend: "downtrend",
    bestStrategy: "continuation",
    strategyOptions: ["continuation", "reversal", "no-trade"],
    idealDirection: "sell",
    pipSize: 0.0001,
    pipValuePerLot: 10,
    defaultAccount: 10000,
    pauseFraction: 0.72,
    hints: ["Bounce in downtrend = sell opportunity", "Not every bounce is reversal"],
    journalPrompt: "Pullback vs reversal in downtrend.",
    reversalGrade: "B",
  },
  {
    id: "rev-jpy-strong-cont",
    title: "USDJPY Trend Resume",
    description: "Clean HH/HL after shallow pullback.",
    symbol: "USDJPY",
    kind: "uptrend",
    seed: "rev-jpy-sc-19",
    category: "continuation",
    behaviour: "continuation",
    tags: ["continuation", "usdjpy"],
    difficulty: "Beginner",
    correctTrend: "uptrend",
    bestStrategy: "continuation",
    strategyOptions: ["continuation", "reversal", "no-trade"],
    idealDirection: "buy",
    pipSize: 0.01,
    pipValuePerLot: 9,
    defaultAccount: 10000,
    pauseFraction: 0.7,
    hints: ["Shallow pullback", "Trend healthy"],
    journalPrompt: "Signs of healthy continuation.",
    reversalGrade: "A",
  },
  {
    id: "rev-eur-assessment-mix",
    title: "Mixed Behaviour Challenge",
    description: "Read the behaviour — trade, wait, or skip?",
    symbol: "EURUSD",
    kind: "downtrend-reversal",
    seed: "rev-eur-mx-20",
    category: "reversal",
    behaviour: "reversal",
    tags: ["assessment", "mixed"],
    difficulty: "Advanced",
    correctTrend: "uptrend",
    bestStrategy: "reversal",
    strategyOptions: ["reversal", "continuation", "range", "no-trade"],
    idealDirection: "buy",
    pipSize: 0.0001,
    pipValuePerLot: 10,
    defaultAccount: 10000,
    pauseFraction: 0.76,
    hints: ["Read all four points first", "Grade quality before executing"],
    journalPrompt: "Full professional workflow review.",
    reversalGrade: "A",
  },
]

export const REVERSAL_EXECUTION_SCENARIOS: ExecutionScenario[] =
  REVERSAL_PACK.map(buildExecutionScenario)

export function getReversalScenarios(): ExecutionScenario[] {
  return REVERSAL_EXECUTION_SCENARIOS
}
