import {
  buildChartCard,
  buildInteractiveChartCard,
} from "@/content/flashcards/card-builder"
import type { Flashcard } from "@/lib/flashcards/types"

const D = "chart-cards"

export const chartCards: Flashcard[] = [
  buildInteractiveChartCard({
    deckId: D,
    slug: "mark-swing-high",
    front: "Mark the swing high on this chart.",
    back: "The local peak where price turned down.",
    explanation: "A swing high has lower highs on both sides.",
    chartScenarioId: "task-mark-swing-high",
    interactiveTask: "Place a marker on the swing high.",
    tags: ["chart", "structure"],
  }),
  buildInteractiveChartCard({
    deckId: D,
    slug: "mark-swing-low",
    front: "Mark the swing low on this chart.",
    back: "The local valley where price turned up.",
    explanation: "A swing low has higher lows on both sides.",
    chartScenarioId: "task-mark-swing-low",
    interactiveTask: "Place a marker on the swing low.",
    tags: ["chart", "structure"],
  }),
  buildInteractiveChartCard({
    deckId: D,
    slug: "identify-support",
    front: "Identify the support zone.",
    back: "The area where buyers repeatedly defended price.",
    explanation: "Support is a floor until broken.",
    chartScenarioId: "task-identify-support",
    interactiveTask: "Mark the support zone.",
    tags: ["chart", "levels"],
  }),
  buildInteractiveChartCard({
    deckId: D,
    slug: "identify-resistance",
    front: "Identify the resistance zone.",
    back: "The area where sellers repeatedly appeared.",
    explanation: "Resistance is a ceiling until broken.",
    chartScenarioId: "task-identify-resistance",
    interactiveTask: "Mark the resistance zone.",
    tags: ["chart", "levels"],
  }),
  buildInteractiveChartCard({
    deckId: D,
    slug: "mark-breakout",
    front: "Where did the breakout happen?",
    back: "Price closed through the range ceiling with momentum.",
    explanation: "Breakouts need follow-through or they trap traders.",
    chartScenarioId: "task-mark-breakout",
    interactiveTask: "Mark the breakout point.",
    tags: ["chart", "breakout"],
  }),
  buildInteractiveChartCard({
    deckId: D,
    slug: "mark-retest",
    front: "Where is the retest?",
    back: "Price returned to the broken level and reacted.",
    explanation: "Retests offer defined-risk entries.",
    chartScenarioId: "task-break-retest",
    interactiveTask: "Mark the retest area.",
    tags: ["chart", "break-retest"],
  }),
  buildChartCard({
    deckId: D,
    slug: "fakeout",
    front: "Is this a fakeout?",
    back: "Yes — price broke the level then closed back inside.",
    explanation: "False breakouts trap breakout traders.",
    chartScenarioId: "demo-fakeout",
    tags: ["chart", "fakeout"],
  }),
  buildInteractiveChartCard({
    deckId: D,
    slug: "risk-reward",
    front: "Place entry, stop loss, and take profit.",
    back: "Entry near support, stop below structure, target at prior high.",
    explanation: "Define all three before clicking buy.",
    chartScenarioId: "task-risk-reward",
    interactiveTask: "Mark entry, stop, and target.",
    tags: ["chart", "risk"],
  }),
  buildInteractiveChartCard({
    deckId: D,
    slug: "icc-phase",
    front: "Which ICC phase is this?",
    back: "Continuation — price resuming after correction.",
    explanation: "Indication → correction → continuation.",
    chartScenarioId: "task-icc-bullish",
    interactiveTask: "Identify the continuation trigger.",
    tags: ["chart", "icc"],
  }),
  buildInteractiveChartCard({
    deckId: D,
    slug: "spot-trend",
    front: "Is this chart trending or ranging?",
    back: "Identify structure from swing highs and lows.",
    explanation: "HH/HL = uptrend; LH/LL = downtrend; flat = range.",
    chartScenarioId: "task-spot-trend",
    interactiveTask: "Mark the trend direction.",
    tags: ["chart", "trend"],
  }),
]
