import { buildBasicCard } from "@/content/flashcards/card-builder"
import type { Flashcard } from "@/lib/flashcards/types"

const D = "reversal-academy"

export const reversalAcademyCards: Flashcard[] = [
  buildBasicCard({
    deckId: D,
    slug: "pullback",
    front: "Pullback?",
    back: "Corrective move against the trend while HH/HL (or LH/LL) stay intact.",
    explanation: "Phase 2 — prepare, don't chase. Structure unchanged.",
    tags: ["behaviour", "pullback"],
  }),
  buildBasicCard({
    deckId: D,
    slug: "reversal",
    front: "Reversal?",
    back: "Trend turns — prior swing sequence breaks (e.g. first LL in uptrend).",
    explanation: "A process: warning → BOS → confirmation → new trend.",
    tags: ["behaviour", "reversal"],
  }),
  buildBasicCard({
    deckId: D,
    slug: "continuation",
    front: "Continuation?",
    back: "Trend resumes after pullback — structure intact.",
    explanation: "Trade with the established direction after confirmation.",
    tags: ["behaviour", "continuation"],
  }),
  buildBasicCard({
    deckId: D,
    slug: "four-point",
    front: "Four-point rule?",
    back: "Latest four swings agree — confirms active trend.",
    explanation: "HH/HL/HH/HL uptrend or LL/LH/LL/LH downtrend.",
    tags: ["structure"],
  }),
  buildBasicCard({
    deckId: D,
    slug: "bos",
    front: "Break of Structure (BOS)?",
    back: "Price breaks the swing that defined the prior trend.",
    explanation: "First structural invalidation — reversal warning.",
    tags: ["structure", "bos"],
  }),
  buildBasicCard({
    deckId: D,
    slug: "choch",
    front: "Change of Character (CHOCH)?",
    back: "First break against immediate micro-structure — early shift signal.",
    explanation: "Often precedes full BOS on higher structure.",
    tags: ["structure", "choch"],
  }),
  buildBasicCard({
    deckId: D,
    slug: "exhaustion",
    front: "Trend exhaustion?",
    back: "Deep pullbacks, weak impulses, sloppy HH/HL progression.",
    explanation: "Market tiring — investigate reversal, don't assume continuation.",
    tags: ["behaviour", "exhaustion"],
  }),
  buildBasicCard({
    deckId: D,
    slug: "liquidity-sweep",
    front: "Liquidity sweep?",
    back: "Price runs stops beyond a swing then reverses sharply.",
    explanation: "Institutions often sweep liquidity before real moves.",
    tags: ["liquidity"],
  }),
  buildBasicCard({
    deckId: D,
    slug: "eod-reversal",
    front: "EOD reversal?",
    back: "Daily-chart reversal at session close with full context workflow.",
    explanation: "Daily bias → phase → exhaustion → structure → execution.",
    tags: ["eod", "reversal"],
  }),
  buildBasicCard({
    deckId: D,
    slug: "false-reversal",
    front: "False reversal?",
    back: "One swing break without follow-through — trap for early reversers.",
    explanation: "Wait for LH/LL or HH/HL confirmation sequence.",
    tags: ["reversal", "trap"],
  }),
  buildBasicCard({
    deckId: D,
    slug: "institutional-confirmation",
    front: "Institutional confirmation?",
    back: "Daily bias, HTF agreement, DXY, sessions, liquidity, news filter.",
    explanation: "Stack context with structure — never trade structure alone.",
    tags: ["professional"],
  }),
  buildBasicCard({
    deckId: D,
    slug: "reversal-grade-a",
    front: "A+ reversal?",
    back: "HTF confluence, liquidity, clean BOS, retest, excellent RR.",
    explanation: "The standard professionals hunt — not every wick.",
    tags: ["grading"],
  }),
  buildBasicCard({
    deckId: D,
    slug: "reversal-grade-d",
    front: "D-grade reversal?",
    back: "Counter-trend, no BOS, no HTF agreement, buying weakness.",
    explanation: "Skip — edge is negative.",
    tags: ["grading"],
  }),
  buildBasicCard({
    deckId: D,
    slug: "continuation-trap",
    front: "Continuation trap?",
    back: "Mistaking every pullback for a reversal — or buying every dip in a dying trend.",
    explanation: "Structure never changed — patience would have saved the account.",
    tags: ["psychology", "trap"],
  }),
  buildBasicCard({
    deckId: D,
    slug: "no-trade",
    front: "When is no-trade correct?",
    back: "Unclear behaviour, unconfirmed structure, conflicting context.",
    explanation: "Skipping is a high-quality decision.",
    tags: ["decisions"],
  }),
]
