import {
  buildBasicCard,
  buildChartCard,
  buildInteractiveChartCard,
  buildMcCard,
} from "@/content/flashcards/card-builder"
import type { Flashcard } from "@/lib/flashcards/types"

const D = "trend-spotter"

export const trendSpotterCards: Flashcard[] = [
  buildBasicCard({
    deckId: D,
    slug: "what-is-uptrend",
    front: "What is an uptrend?",
    back: "A series of higher highs and higher lows.",
    explanation: "Buyers control when each swing low holds above the prior low.",
    tags: ["trend"],
    source: "trend-spotter",
  }),
  buildBasicCard({
    deckId: D,
    slug: "what-is-downtrend",
    front: "What is a downtrend?",
    back: "A series of lower highs and lower lows.",
    explanation: "Sellers control when rallies fail below prior swing highs.",
    tags: ["trend"],
    source: "trend-spotter",
  }),
  buildBasicCard({
    deckId: D,
    slug: "what-is-range",
    front: "What is a range?",
    back: "Price oscillates between similar highs and lows without clear direction.",
    explanation: "Ranges have a ceiling and floor — not a sustained trend.",
    tags: ["trend"],
    source: "trend-spotter",
  }),
  buildBasicCard({
    deckId: D,
    slug: "higher-high",
    front: "What is a higher high?",
    back: "A peak above the previous peak.",
    explanation: "HHs confirm bullish structure in an uptrend.",
    tags: ["structure"],
    source: "trend-spotter",
  }),
  buildBasicCard({
    deckId: D,
    slug: "higher-low",
    front: "What is a higher low?",
    back: "A valley above the previous valley.",
    explanation: "HLs show buyers defending dips in an uptrend.",
    tags: ["structure"],
    source: "trend-spotter",
  }),
  buildBasicCard({
    deckId: D,
    slug: "lower-high",
    front: "What is a lower high?",
    back: "A peak below the previous peak.",
    explanation: "LHs confirm sellers in control during a downtrend.",
    tags: ["structure"],
    source: "trend-spotter",
  }),
  buildBasicCard({
    deckId: D,
    slug: "lower-low",
    front: "What is a lower low?",
    back: "A valley below the previous valley.",
    explanation: "LLs confirm bearish structure.",
    tags: ["structure"],
    source: "trend-spotter",
  }),
  buildBasicCard({
    deckId: D,
    slug: "structure-break",
    front: "What is a structure break?",
    back: "Price breaks a key swing level, potentially changing trend bias.",
    explanation: "Breaking the last HL in an uptrend shifts bias bearish.",
    tags: ["structure"],
    source: "trend-spotter",
  }),
  buildBasicCard({
    deckId: D,
    slug: "pullback",
    front: "What is a pullback?",
    back: "A temporary move against the dominant trend before continuation.",
    explanation: "Pullbacks retest prior levels — they are not always reversals.",
    tags: ["trend"],
    source: "trend-spotter",
  }),
  buildBasicCard({
    deckId: D,
    slug: "when-skip",
    front: "When should you skip a chart?",
    back: "When structure is messy, ranging, or low-confidence.",
    explanation: "No clear trend = no high-quality trading environment for beginners.",
    tags: ["discipline"],
    source: "trend-spotter",
  }),
  buildChartCard({
    deckId: D,
    slug: "identify-trend",
    front: "Identify this trend",
    back: "Study swing highs and lows to classify direction.",
    explanation: "Look for HH/HL (uptrend) or LH/LL (downtrend).",
    chartScenarioId: "task-spot-trend",
    tags: ["chart"],
    source: "trend-spotter",
  }),
  buildInteractiveChartCard({
    deckId: D,
    slug: "mark-swing-high",
    front: "Mark the swing high",
    back: "Place a marker at the local peak.",
    explanation: "Swing highs have lower highs on both sides.",
    chartScenarioId: "demo-swing-high-low",
    interactiveTask: "Mark the most recent swing high.",
    tags: ["chart"],
    source: "trend-spotter",
  }),
  buildInteractiveChartCard({
    deckId: D,
    slug: "mark-swing-low",
    front: "Mark the swing low",
    back: "Place a marker at the local valley.",
    explanation: "Swing lows have higher lows on both sides.",
    chartScenarioId: "task-mark-swing-low",
    interactiveTask: "Mark the most recent swing low.",
    tags: ["chart"],
    source: "trend-spotter",
  }),
  buildMcCard({
    deckId: D,
    slug: "trend-or-range",
    front: "Is this a trend or range?",
    back: "Range — price rejects the same ceiling and floor.",
    explanation: "No sustained new highs or lows = range.",
    options: [
      { id: "a", text: "Uptrend" },
      { id: "b", text: "Downtrend" },
      { id: "c", text: "Range" },
      { id: "d", text: "Messy" },
    ],
    correctAnswer: "c",
    tags: ["chart"],
    source: "trend-spotter",
  }),
  buildMcCard({
    deckId: D,
    slug: "pullback-or-reversal",
    front: "Is this a pullback or reversal?",
    back: "Pullback — the broader uptrend structure is still intact.",
    explanation: "A dip within HH/HL structure is usually a pullback.",
    options: [
      { id: "a", text: "Pullback in uptrend" },
      { id: "b", text: "Bearish reversal" },
      { id: "c", text: "Range" },
      { id: "d", text: "Cannot tell — skip" },
    ],
    correctAnswer: "a",
    tags: ["trend"],
    source: "trend-spotter",
  }),
]
