import type { ChartAnnotation } from "@/lib/charts/types"

import type { ScenarioDraft } from "./types"
import { annotationsToChartAnnotations } from "./types"

function formatAnnotations(annotations: ChartAnnotation[]): string {
  if (annotations.length === 0) return "[]"
  const rows = annotations.map((a) => {
    const parts = [
      `id: ${JSON.stringify(a.id)}`,
      `type: ${JSON.stringify(a.type)}`,
      `index: ${a.index}`,
      `price: ${a.price}`,
    ]
    if ("text" in a && a.text) parts.push(`text: ${JSON.stringify(a.text)}`)
    return `    { ${parts.join(", ")} },`
  })
  return `[\n${rows.join("\n")}\n  ]`
}

function formatCandles(candles: ScenarioDraft["candles"]): string {
  const rows = candles.map(
    (c) =>
      `    { time: ${c.time}, open: ${c.open}, high: ${c.high}, low: ${c.low}, close: ${c.close} },`
  )
  return `[\n${rows.join("\n")}\n  ]`
}

function formatStringArray(items: string[], emptyFallback = "[]"): string {
  if (items.length === 0) return emptyFallback
  return `[\n${items.map((s) => `    ${JSON.stringify(s)},`).join("\n")}\n  ]`
}

/** Generate copy-paste TypeScript for a custom Execution Lab scenario. */
export function exportScenarioTypeScript(draft: ScenarioDraft): string {
  const slug = draft.id.replace(/[^a-z0-9-]/gi, "-").toLowerCase()
  const varName = slug.replace(/-([a-z])/g, (_, c: string) => c.toUpperCase()).replace(/-/g, "")

  const chartAnnotations = annotationsToChartAnnotations(draft.annotations)

  return `/**
 * Generated by Scenario Builder — paste into content/execution-lab/<pack>.ts
 * Then register in content/execution-lab/scenarios.ts or ALL_EXECUTION_SCENARIOS.
 */
import type { ExecutionScenario } from "@/lib/execution-lab/types"
import type { ChartScenario } from "@/lib/charts/types"

const CANDLES = ${formatCandles(draft.candles)}

const CHART: ChartScenario = {
  id: ${JSON.stringify(draft.id)},
  title: ${JSON.stringify(draft.title)},
  description: ${JSON.stringify(draft.description)},
  symbol: ${JSON.stringify(draft.symbol)},
  timeframe: ${JSON.stringify(draft.timeframe)},
  concept: ${JSON.stringify(draft.category === "break-retest" ? "break-retest" : "trend")},
  candles: CANDLES,
  annotations: ${formatAnnotations(chartAnnotations)},
  hints: ${formatStringArray(draft.hints)},
  explanation: ${JSON.stringify(draft.description)},
  difficulty: ${JSON.stringify(draft.difficulty === "Beginner" ? "beginner" : "intermediate")},
  estimatedMinutes: 8,
}

export const ${varName}Scenario: ExecutionScenario = {
  id: ${JSON.stringify(draft.id)},
  title: ${JSON.stringify(draft.title)},
  description: ${JSON.stringify(draft.description)},
  symbol: ${JSON.stringify(draft.symbol)},
  timeframe: ${JSON.stringify(draft.timeframe)},
  category: ${JSON.stringify(draft.category)},
  difficulty: ${JSON.stringify(draft.difficulty)},
  chart: CHART,
  pauseIndex: ${draft.pauseIndex},
  replayEndIndex: ${Math.max(0, draft.candles.length - 1)},
  correctTrend: ${JSON.stringify(draft.correctTrend)},
  bestStrategy: ${JSON.stringify(draft.bestStrategy)},
  strategyOptions: ${formatStringArray(draft.strategyOptions)},
  idealDirection: ${JSON.stringify(draft.idealDirection)},
  idealEntry: ${draft.idealEntry},
  idealStop: ${draft.idealStop},
  idealTarget: ${draft.idealTarget},
  pipSize: ${draft.pipSize},
  pipValuePerLot: ${draft.pipValuePerLot},
  defaultAccount: ${draft.defaultAccount},
  hints: ${formatStringArray(draft.hints)},
  behaviour: ${JSON.stringify(draft.behaviour)},
  subcategory: ${draft.subcategory ? JSON.stringify(draft.subcategory) : "undefined"},
  tags: ${draft.tags.length > 0 ? formatStringArray(draft.tags) : "undefined"},
  journalPrompt: ${draft.journalPrompt ? JSON.stringify(draft.journalPrompt) : "undefined"},${
    draft.reversalGrade
      ? `\n  reversalGrade: ${JSON.stringify(draft.reversalGrade)},`
      : ""
  }
}

// Common mistakes (coaching metadata — add to mentor copy as needed):
// ${draft.commonMistakes.map((m) => JSON.stringify(m)).join("\n// ") || "none"}

// Session: ${draft.session}
// No-trade valid: ${draft.noTradeValid}
// Market label: ${draft.market}
`
}
