import type { CourseQuiz } from "@/lib/course/types"

const PATH_ID = "market-behaviour-academy"

/** Reversal Academy milestone — 20 mixed behaviour scenarios. */
export const reversalAcademyAssessment: CourseQuiz = {
  id: "reversal-academy-assessment",
  lessonId: "mba-reversal-quiz",
  pathId: PATH_ID,
  title: "Reversal Academy Assessment",
  description:
    "Pullback vs reversal, structure breaks, continuation traps, quality grading, and when to skip.",
  passingScore: 85,
  xpReward: 150,
  questions: [
    {
      id: "q1",
      type: "multiple-choice",
      question: "What is a reversal in professional terms?",
      options: [
        { id: "a", text: "One large red candle" },
        { id: "b", text: "A process: weakening trend → structure break → confirmation → new trend" },
        { id: "c", text: "Any pullback in an uptrend" },
        { id: "d", text: "RSI below 30" },
      ],
      correctAnswer: "b",
      explanation:
        "Reversals unfold as a sequence. One candle or indicator reading is never enough.",
      relatedConcept: "Reversal process",
    },
    {
      id: "q2",
      type: "scenario",
      question: "Uptrend: HH, HL, HH, HL — then price prints a lower low. What is this?",
      options: [
        { id: "a", text: "Confirmed reversal — sell immediately" },
        { id: "b", text: "Healthy pullback — buy the dip" },
        { id: "c", text: "Reversal warning — structure broke, need confirmation" },
        { id: "d", text: "Range" },
      ],
      correctAnswer: "c",
      explanation:
        "The first lower low breaks the higher-low sequence. Warning only — wait for LH/LL confirmation.",
      relatedConcept: "Structure break",
    },
    {
      id: "q3",
      type: "multiple-choice",
      question: "Pullback vs reversal — the key difference is:",
      options: [
        { id: "a", text: "Pullback candle colour" },
        { id: "b", text: "Whether HH/HL (or LH/LL) structure stays intact" },
        { id: "c", text: "Volume on the candle" },
        { id: "d", text: "Time of day only" },
      ],
      correctAnswer: "b",
      explanation: "Structure tells you if buyers/sellers still control — not candle cosmetics.",
      relatedConcept: "Pullback vs reversal",
    },
    {
      id: "q4",
      type: "scenario",
      question: "Two charts look similar. Chart A: HL holds. Chart B: HL breaks. Which do you trade for continuation?",
      options: [
        { id: "a", text: "Chart B" },
        { id: "b", text: "Chart A" },
        { id: "c", text: "Both" },
        { id: "d", text: "Neither — always reverse" },
      ],
      correctAnswer: "b",
      explanation: "Continuation requires intact structure. Chart B is reversal territory.",
      relatedConcept: "Continuation trap",
    },
    {
      id: "q5",
      type: "multiple-choice",
      question: "The four-point rule confirms a trend when:",
      options: [
        { id: "a", text: "Any four candles agree" },
        { id: "b", text: "Four consecutive swing points agree (HH/HL/HH/HL or mirror)" },
        { id: "c", text: "Four indicators align" },
        { id: "d", text: "Four hours pass" },
      ],
      correctAnswer: "b",
      explanation: "Four structural turning points in agreement define the active trend.",
      relatedConcept: "Four-point rule",
    },
    {
      id: "q6",
      type: "scenario",
      question: "After one LL in an uptrend, is the reversal confirmed?",
      options: [
        { id: "a", text: "Yes — reverse now" },
        { id: "b", text: "No — need a lower high to confirm bearish structure" },
        { id: "c", text: "Yes if RSI is overbought" },
        { id: "d", text: "Always wait 24 hours" },
      ],
      correctAnswer: "b",
      explanation: "One broken swing is a warning. LH + LL sequence confirms the reversal.",
      relatedConcept: "Confirmation",
    },
    {
      id: "q7",
      type: "multiple-choice",
      question: "Break of Structure (BOS) means:",
      options: [
        { id: "a", text: "Price breaks a key swing level against the prior trend" },
        { id: "b", text: "A gap on the chart" },
        { id: "c", text: "News release" },
        { id: "d", text: "Moving average cross" },
      ],
      correctAnswer: "a",
      explanation: "BOS is structural — price invalidates the prior swing that defined the trend.",
      relatedConcept: "BOS",
    },
    {
      id: "q8",
      type: "scenario",
      question: "Beginner buys every dip in a weakening uptrend. Price never makes a new HH. Outcome?",
      options: [
        { id: "a", text: "Usually wins — dips always recover" },
        { id: "b", text: "Catching falling knives — structure never confirmed reversal but trend failed" },
        { id: "c", text: "Guaranteed profit with tight stops" },
        { id: "d", text: "Irrelevant — only EMA matters" },
      ],
      correctAnswer: "b",
      explanation: "Buying weakness without structure change is the continuation trap in reverse.",
      relatedConcept: "Continuation trap",
    },
    {
      id: "q9",
      type: "multiple-choice",
      question: "An A+ reversal typically includes:",
      options: [
        { id: "a", text: "HTF confluence, liquidity sweep, clean BOS, retest, excellent RR" },
        { id: "b", text: "Counter-trend with no confirmation" },
        { id: "c", text: "Buying the first red candle" },
        { id: "d", text: "Trading against DXY with no structure" },
      ],
      correctAnswer: "a",
      explanation: "Grade reversals on structure, confluence, liquidity, and risk — not hope.",
      relatedConcept: "Reversal quality",
    },
    {
      id: "q10",
      type: "scenario",
      question: "A D-grade reversal setup is best described as:",
      options: [
        { id: "a", text: "Counter-trend, no BOS, no HTF agreement" },
        { id: "b", text: "Institutional with liquidity and retest" },
        { id: "c", text: "London open with DXY alignment" },
        { id: "d", text: "Four-point confirmed with shallow pullback" },
      ],
      correctAnswer: "a",
      explanation: "Low-quality reversals fight structure and context — professionals skip.",
      relatedConcept: "Reversal grading",
    },
    {
      id: "q11",
      type: "multiple-choice",
      question: "Institutional confirmation includes:",
      options: [
        { id: "a", text: "Daily bias, HTF agreement, DXY, sessions, liquidity" },
        { id: "b", text: "Only the 5-minute chart" },
        { id: "c", text: "Social media sentiment" },
        { id: "d", text: "Random entry" },
      ],
      correctAnswer: "a",
      explanation: "Context stacks probability — structure alone is not enough at the professional level.",
      relatedConcept: "Institutional confirmation",
    },
    {
      id: "q12",
      type: "scenario",
      question: "EURUSD uptrend but DXY ripping higher. Best action on a reversal long?",
      options: [
        { id: "a", text: "Take full size — chart looks good" },
        { id: "b", text: "Reduce size or skip — correlation disagrees" },
        { id: "c", text: "Ignore DXY" },
        { id: "d", text: "Double down" },
      ],
      correctAnswer: "b",
      explanation: "When macro context contradicts the pair thesis, edge shrinks dramatically.",
      relatedConcept: "DXY agreement",
    },
    {
      id: "q13",
      type: "multiple-choice",
      question: "False reversal signal — best filter:",
      options: [
        { id: "a", text: "One swing break without follow-through" },
        { id: "b", text: "Enter on first LL always" },
        { id: "c", text: "Ignore higher timeframe" },
        { id: "d", text: "Trade every liquidity wick" },
      ],
      correctAnswer: "a",
      explanation: "Wait for the full bearish/bullish sequence — traps punish early callers.",
      relatedConcept: "False reversal",
    },
    {
      id: "q14",
      type: "scenario",
      question: "Overlapping swings, no clear HH/HL or LH/LL. Behaviour?",
      options: [
        { id: "a", text: "Strong trend" },
        { id: "b", text: "Range — no trade unless range playbook" },
        { id: "c", text: "Must reverse" },
        { id: "d", text: "Must continue" },
      ],
      correctAnswer: "b",
      explanation: "No directional edge — standing aside is a professional decision.",
      relatedConcept: "Range",
    },
    {
      id: "q15",
      type: "multiple-choice",
      question: "Trend exhaustion often shows as:",
      options: [
        { id: "a", text: "Shallow pullbacks and clean impulses" },
        { id: "b", text: "Deep pullbacks, weak breaks, momentum fading" },
        { id: "c", text: "Perfect HH/HL forever" },
        { id: "d", text: "Only on Fridays" },
      ],
      correctAnswer: "b",
      explanation: "Weakening momentum and sloppy structure precede many reversals.",
      relatedConcept: "Exhaustion",
    },
    {
      id: "q16",
      type: "scenario",
      question: "Liquidity sweep above highs then sharp rejection with BOS. This supports:",
      options: [
        { id: "a", text: "Blind continuation long" },
        { id: "b", text: "Bearish reversal thesis with confluence" },
        { id: "c", text: "Ignore liquidity" },
        { id: "d", text: "No structure needed" },
      ],
      correctAnswer: "b",
      explanation: "Sweep + structure break + rejection is classic institutional reversal anatomy.",
      relatedConcept: "Liquidity sweep",
    },
    {
      id: "q17",
      type: "multiple-choice",
      question: "EOD reversal differs from intraday reversal because:",
      options: [
        { id: "a", text: "EOD uses daily context, exhaustion, and fewer decisions per day" },
        { id: "b", text: "EOD ignores structure" },
        { id: "c", text: "Intraday never needs confirmation" },
        { id: "d", text: "They are identical" },
      ],
      correctAnswer: "a",
      explanation: "EOD workflow layers daily bias, phase, and patience — not scalp speed.",
      relatedConcept: "EOD reversal",
    },
    {
      id: "q18",
      type: "scenario",
      question: "Healthy continuation in an uptrend — best behaviour label?",
      options: [
        { id: "a", text: "Reversal" },
        { id: "b", text: "Pullback within trend" },
        { id: "c", text: "Exhaustion" },
        { id: "d", text: "No trade always" },
      ],
      correctAnswer: "b",
      explanation: "HL holds, structure intact — this is a pullback, not a reversal.",
      relatedConcept: "Continuation",
    },
    {
      id: "q19",
      type: "multiple-choice",
      question: "When should you wait instead of trade?",
      options: [
        { id: "a", text: "Unconfirmed structure, conflicting HTF, or unclear behaviour" },
        { id: "b", text: "Never — always be in the market" },
        { id: "c", text: "Only when profitable" },
        { id: "d", text: "When bored" },
      ],
      correctAnswer: "a",
      explanation: "Patience is edge. Professionals wait for A+ conditions.",
      relatedConcept: "Patience",
    },
    {
      id: "q20",
      type: "scenario",
      question: "London session reversal with 4H agreement, clean BOS, retest, 1:3 RR. Grade?",
      options: [
        { id: "a", text: "A+ institutional" },
        { id: "b", text: "D counter-trend" },
        { id: "c", text: "Skip always" },
        { id: "d", text: "Random" },
      ],
      correctAnswer: "a",
      explanation: "Stacked confluence with structure and RR — this is the standard to hunt.",
      relatedConcept: "A+ reversal",
    },
  ],
}
