import type { LearningNode } from "@/lib/learning-map/types"

export const LEARNING_NODES: LearningNode[] = [
  {
    id: "node-lesson-what-is-trading",
    slug: "what-is-trading",
    title: "What is Trading?",
    type: "lesson",
    level: "beginner",
    refId: "tf-m1-what-is-trading",
    href: "/paths/trading-foundations/lessons/what-is-trading",
    prerequisites: [],
    unlocks: ["node-lesson-what-moves-price"],
    xpReward: 25,
    stageId: "stage-market-basics",
  },
  {
    id: "node-lesson-what-moves-price",
    slug: "what-moves-price",
    title: "What Moves Price?",
    type: "lesson",
    level: "beginner",
    refId: "tf-m1-what-moves-price",
    href: "/paths/trading-foundations/lessons/what-moves-price",
    prerequisites: ["node-lesson-what-is-trading"],
    unlocks: ["node-quiz-basics"],
    xpReward: 25,
    stageId: "stage-market-basics",
  },
  {
    id: "node-quiz-basics",
    slug: "trading-basics-check",
    title: "Trading Basics Quiz",
    type: "quiz",
    level: "beginner",
    refId: "tf-m1-quiz-basics",
    href: "/paths/trading-foundations/lessons/trading-basics-check",
    prerequisites: ["node-lesson-what-moves-price"],
    unlocks: ["node-lesson-candle-anatomy"],
    xpReward: 30,
    stageId: "stage-market-basics",
  },
  {
    id: "node-lesson-candle-anatomy",
    slug: "candlestick-anatomy",
    title: "Candlestick Anatomy",
    type: "lesson",
    level: "beginner",
    refId: "tf-m2-candle-anatomy",
    href: "/paths/trading-foundations/lessons/candlestick-anatomy",
    prerequisites: ["node-quiz-basics"],
    unlocks: ["node-lesson-bullish-bearish"],
    xpReward: 25,
    stageId: "stage-candlesticks",
  },
  {
    id: "node-lesson-bullish-bearish",
    slug: "bullish-vs-bearish-candles",
    title: "Bullish vs Bearish Candles",
    type: "lesson",
    level: "beginner",
    refId: "tf-m2-bullish-bearish",
    href: "/paths/trading-foundations/lessons/bullish-vs-bearish-candles",
    prerequisites: ["node-lesson-candle-anatomy"],
    unlocks: ["node-quiz-candles"],
    xpReward: 25,
    stageId: "stage-candlesticks",
  },
  {
    id: "node-quiz-candles",
    slug: "candlestick-basics-quiz",
    title: "Candlestick Basics Quiz",
    type: "quiz",
    level: "beginner",
    refId: "tf-m2-quiz-candles",
    href: "/paths/trading-foundations/lessons/candlestick-basics-quiz",
    prerequisites: ["node-lesson-bullish-bearish"],
    unlocks: ["node-lesson-swing-highs"],
    xpReward: 30,
    stageId: "stage-candlesticks",
  },
  {
    id: "node-lesson-swing-highs",
    slug: "swing-highs-and-lows",
    title: "Swing Highs and Swing Lows",
    type: "lesson",
    level: "beginner",
    refId: "tf-m3-swing-highs-lows",
    href: "/paths/trading-foundations/lessons/swing-highs-and-lows",
    prerequisites: ["node-quiz-candles"],
    unlocks: ["node-lesson-trends-ranges"],
    xpReward: 30,
    stageId: "stage-market-structure",
  },
  {
    id: "node-lesson-trends-ranges",
    slug: "trends-vs-ranges",
    title: "Trends vs Ranges",
    type: "lesson",
    level: "beginner",
    refId: "tf-m3-trends-ranges",
    href: "/paths/trading-foundations/lessons/trends-vs-ranges",
    prerequisites: ["node-lesson-swing-highs"],
    unlocks: ["node-drill-spot-trend", "node-trend-what-is"],
    xpReward: 30,
    stageId: "stage-market-structure",
  },
  {
    id: "node-drill-spot-trend",
    slug: "spot-the-trend",
    title: "First Chart Drill: Spot the Trend",
    type: "chart-drill",
    level: "beginner",
    refId: "tf-m3-drill-trend",
    href: "/paths/trading-foundations/lessons/spot-the-trend",
    prerequisites: ["node-lesson-trends-ranges"],
    unlocks: [],
    xpReward: 35,
    stageId: "stage-market-structure",
  },
  {
    id: "node-trend-what-is",
    slug: "what-is-a-trend",
    title: "What is a Trend?",
    type: "trend-lesson",
    level: "beginner",
    refId: "ts-what-is-a-trend",
    href: "/trend-spotter/lessons/what-is-a-trend",
    prerequisites: ["node-lesson-trends-ranges"],
    unlocks: ["node-trend-up-vs-down"],
    xpReward: 30,
    stageId: "stage-trend-detection",
  },
  {
    id: "node-trend-up-vs-down",
    slug: "uptrend-vs-downtrend",
    title: "Uptrend vs Downtrend",
    type: "trend-lesson",
    level: "beginner-plus",
    refId: "ts-uptrend-vs-downtrend",
    href: "/trend-spotter/lessons/uptrend-vs-downtrend",
    prerequisites: ["node-trend-what-is"],
    unlocks: ["node-trend-vs-range"],
    xpReward: 30,
    stageId: "stage-trend-detection",
  },
  {
    id: "node-trend-vs-range",
    slug: "trend-vs-range",
    title: "Trend vs Range",
    type: "trend-lesson",
    level: "beginner-plus",
    refId: "ts-trend-vs-range",
    href: "/trend-spotter/lessons/trend-vs-range",
    prerequisites: ["node-trend-up-vs-down"],
    unlocks: ["node-trend-challenge"],
    xpReward: 30,
    stageId: "stage-trend-detection",
  },
  {
    id: "node-trend-challenge",
    slug: "trend-challenge",
    title: "10-Chart Trend Challenge",
    type: "challenge",
    level: "intermediate",
    refId: "trend-10-chart",
    href: "/trend-spotter/challenge",
    prerequisites: ["node-trend-vs-range"],
    unlocks: [],
    xpReward: 50,
    stageId: "stage-intermediate-mastery",
  },
  {
    id: "node-chart-support",
    slug: "identify-support",
    title: "Identify Support",
    type: "chart-drill",
    level: "beginner-plus",
    refId: "task-identify-support",
    href: "/chart-lab/task-identify-support",
    prerequisites: ["node-trend-vs-range"],
    unlocks: ["node-chart-resistance"],
    xpReward: 35,
    stageId: "stage-support-resistance",
  },
  {
    id: "node-chart-resistance",
    slug: "identify-resistance",
    title: "Identify Resistance",
    type: "chart-drill",
    level: "beginner-plus",
    refId: "task-identify-resistance",
    href: "/chart-lab/task-identify-resistance",
    prerequisites: ["node-chart-support"],
    unlocks: ["node-strategy-support-bounce"],
    xpReward: 35,
    stageId: "stage-support-resistance",
  },
  {
    id: "node-chart-breakout",
    slug: "mark-breakout",
    title: "Mark a Breakout",
    type: "chart-drill",
    level: "intermediate",
    refId: "task-mark-breakout",
    href: "/chart-lab/task-mark-breakout",
    previewHref: "/chart-lab/demo-breakout",
    prerequisites: ["node-chart-resistance"],
    unlocks: ["node-chart-fakeout"],
    xpReward: 40,
    stageId: "stage-breakouts-fakeouts",
  },
  {
    id: "node-chart-fakeout",
    slug: "fake-reversals",
    title: "Spot Fake Reversals",
    type: "trend-lesson",
    level: "intermediate",
    refId: "ts-fake-reversals",
    href: "/trend-spotter/lessons/fake-reversals",
    previewHref: "/chart-lab/demo-fakeout",
    prerequisites: ["node-chart-breakout"],
    unlocks: ["node-strategy-break-retest"],
    xpReward: 40,
    stageId: "stage-breakouts-fakeouts",
  },
  {
    id: "node-lesson-what-is-risk",
    slug: "what-is-risk",
    title: "What is Risk?",
    type: "lesson",
    level: "beginner",
    refId: "tf-m4-what-is-risk",
    href: "/paths/trading-foundations/lessons/what-is-risk",
    prerequisites: ["node-lesson-trends-ranges"],
    unlocks: ["node-lesson-risk-reward"],
    xpReward: 25,
    stageId: "stage-risk-management",
  },
  {
    id: "node-lesson-risk-reward",
    slug: "risk-reward-explained",
    title: "Risk/Reward Explained",
    type: "lesson",
    level: "beginner",
    refId: "tf-m4-risk-reward",
    href: "/paths/trading-foundations/lessons/risk-reward-explained",
    prerequisites: ["node-lesson-what-is-risk"],
    unlocks: ["node-book-risk-reward"],
    xpReward: 30,
    stageId: "stage-risk-management",
  },
  {
    id: "node-lesson-interactive-rr",
    slug: "interactive-risk-reward",
    title: "Interactive Risk/Reward",
    type: "lesson",
    level: "beginner",
    refId: "tf-m4-interactive-rr",
    href: "/paths/trading-foundations/lessons/calculate-risk-reward",
    prerequisites: ["node-lesson-risk-reward"],
    unlocks: [],
    xpReward: 35,
    stageId: "stage-risk-management",
  },
  {
    id: "node-book-risk-reward",
    slug: "risk-reward-ratio",
    title: "Risk/Reward Ratio (Book Lab)",
    type: "book-concept",
    level: "beginner",
    refId: "bl-risk-reward-ratio",
    href: "/library/day-trading-for-a-living/risk-reward-ratio",
    prerequisites: ["node-lesson-risk-reward"],
    unlocks: [],
    xpReward: 25,
    stageId: "stage-risk-management",
  },
  {
    id: "node-strategy-support-bounce",
    slug: "support-bounce",
    title: "Support Bounce Strategy",
    type: "strategy",
    level: "beginner-plus",
    refId: "support-bounce",
    href: "/strategy-wiki/support-bounce",
    previewHref: "/strategy-wiki/support-bounce",
    prerequisites: ["node-chart-resistance"],
    unlocks: ["node-strategy-break-retest-practice"],
    xpReward: 40,
    stageId: "stage-strategy-practice",
  },
  {
    id: "node-strategy-break-retest",
    slug: "break-retest",
    title: "Break & Retest Strategy",
    type: "strategy",
    level: "intermediate",
    refId: "break-retest",
    href: "/strategy-wiki/break-retest",
    previewHref: "/strategy-wiki/break-retest",
    prerequisites: ["node-chart-fakeout", "node-lesson-risk-reward"],
    unlocks: ["node-strategy-break-retest-practice"],
    xpReward: 45,
    stageId: "stage-break-retest",
  },
  {
    id: "node-strategy-break-retest-practice",
    slug: "break-retest-practice",
    title: "Break & Retest Practice",
    type: "strategy",
    level: "intermediate",
    refId: "break-retest-practice",
    href: "/strategy-wiki/break-retest/practice",
    prerequisites: ["node-strategy-break-retest"],
    unlocks: ["node-flashcards-break-retest"],
    xpReward: 50,
    stageId: "stage-break-retest",
  },
  {
    id: "node-lesson-icc-indication",
    slug: "icc-indication",
    title: "ICC: Indication",
    type: "lesson",
    level: "intermediate",
    refId: "icc-m1-indication",
    href: "/paths/icc-strategy/lessons/indication",
    prerequisites: ["node-strategy-break-retest-practice", "node-trend-vs-range"],
    unlocks: ["node-strategy-icc"],
    xpReward: 35,
    stageId: "stage-icc-foundations",
  },
  {
    id: "node-strategy-icc",
    slug: "icc",
    title: "ICC Strategy",
    type: "strategy",
    level: "intermediate",
    refId: "icc",
    href: "/strategy-wiki/icc",
    previewHref: "/strategy-wiki/icc",
    prerequisites: ["node-lesson-icc-indication"],
    unlocks: [],
    xpReward: 50,
    stageId: "stage-icc-foundations",
  },
  {
    id: "node-strategy-challenge",
    slug: "strategy-challenge",
    title: "Strategy Challenge Mode",
    type: "challenge",
    level: "intermediate",
    refId: "strategy-challenge",
    href: "/strategy-wiki/support-bounce/challenge",
    prerequisites: ["node-strategy-support-bounce"],
    unlocks: [],
    xpReward: 50,
    stageId: "stage-strategy-practice",
  },
  {
    id: "node-strategy-challenge-advanced",
    slug: "strategy-challenge-advanced",
    title: "Advanced Strategy Challenge",
    type: "challenge",
    level: "advanced",
    refId: "strategy-challenge-advanced",
    href: "/strategy-wiki/break-retest/challenge",
    prerequisites: ["node-strategy-break-retest-practice"],
    unlocks: [],
    xpReward: 60,
    stageId: "stage-intermediate-mastery",
  },
  {
    id: "node-journal-first",
    slug: "first-journal",
    title: "First Journal Reflection",
    type: "journal",
    level: "beginner",
    refId: "journal-first",
    href: "/journal/new",
    prerequisites: [],
    unlocks: [],
    xpReward: 20,
    stageId: "stage-psychology-journaling",
  },
  {
    id: "node-lesson-reflection",
    slug: "reflection",
    title: "Path Reflection",
    type: "lesson",
    level: "beginner-plus",
    refId: "tf-m5-reflection",
    href: "/paths/trading-foundations/lessons/beginner-trading-rules",
    prerequisites: ["node-lesson-risk-reward"],
    unlocks: [],
    xpReward: 25,
    stageId: "stage-psychology-journaling",
  },
  {
    id: "node-book-psychology",
    slug: "building-consistency",
    title: "Building Consistency (Book Lab)",
    type: "book-concept",
    level: "beginner-plus",
    refId: "bl-building-consistency",
    href: "/library/day-trading-for-a-living/building-consistency",
    prerequisites: ["node-journal-first"],
    unlocks: [],
    xpReward: 25,
    stageId: "stage-psychology-journaling",
  },
  {
    id: "node-flashcards-break-retest",
    slug: "break-retest-deck",
    title: "Break & Retest Flashcards",
    type: "flashcard-deck",
    level: "intermediate",
    refId: "deck-break-retest",
    href: "/flashcards/session?deck=break-retest",
    prerequisites: ["node-strategy-break-retest-practice"],
    unlocks: [],
    xpReward: 20,
    stageId: "stage-break-retest",
  },
  {
    id: "node-flashcards-mastery",
    slug: "mastery-review",
    title: "Mastery Review Session",
    type: "flashcard-deck",
    level: "advanced",
    refId: "deck-market-structure",
    href: "/flashcards/session?deck=market-structure",
    prerequisites: ["node-trend-challenge"],
    unlocks: ["node-lesson-market-context"],
    xpReward: 25,
    stageId: "stage-intermediate-mastery",
  },
  // ---- Professional Forex track (Stages 13–17) ----
  {
    id: "node-lesson-market-context",
    slug: "what-is-market-context",
    title: "What is Market Context?",
    type: "lesson",
    level: "advanced",
    refId: "pf-m1-market-context",
    href: "/paths/professional-forex/lessons/what-is-market-context",
    prerequisites: ["node-flashcards-mastery"],
    unlocks: ["node-lesson-daily-direction"],
    xpReward: 35,
    stageId: "stage-market-context",
  },
  {
    id: "node-lesson-daily-direction",
    slug: "daily-direction",
    title: "Daily Direction & DXY",
    type: "lesson",
    level: "advanced",
    refId: "pf-m1-daily-direction",
    href: "/paths/professional-forex/lessons/daily-direction",
    prerequisites: ["node-lesson-market-context"],
    unlocks: ["node-quiz-market-context"],
    xpReward: 35,
    stageId: "stage-market-context",
  },
  {
    id: "node-quiz-market-context",
    slug: "market-context-check",
    title: "Market Context Check",
    type: "quiz",
    level: "advanced",
    refId: "pf-m1-quiz",
    href: "/paths/professional-forex/lessons/market-context-check",
    prerequisites: ["node-lesson-daily-direction"],
    unlocks: ["node-lesson-htf-agreement"],
    xpReward: 50,
    stageId: "stage-market-context",
  },
  {
    id: "node-lesson-htf-agreement",
    slug: "higher-timeframe-agreement",
    title: "Higher Timeframe Agreement",
    type: "lesson",
    level: "advanced",
    refId: "pf-m2-htf-agreement",
    href: "/paths/professional-forex/lessons/higher-timeframe-agreement",
    prerequisites: ["node-quiz-market-context"],
    unlocks: ["node-lesson-phase1-phase2"],
    xpReward: 35,
    stageId: "stage-positioning",
  },
  {
    id: "node-lesson-phase1-phase2",
    slug: "phase-1-vs-phase-2",
    title: "Phase 1 vs Phase 2",
    type: "lesson",
    level: "advanced",
    refId: "pf-m2-phase1-phase2",
    href: "/paths/professional-forex/lessons/phase-1-vs-phase-2",
    prerequisites: ["node-lesson-htf-agreement"],
    unlocks: ["node-chart-four-point-trend", "node-quiz-positioning"],
    xpReward: 35,
    stageId: "stage-positioning",
  },
  {
    id: "node-chart-four-point-trend",
    slug: "four-point-trend",
    title: "Confirm the Four-Point Trend",
    type: "chart-drill",
    level: "advanced",
    refId: "task-four-point-trend",
    href: "/chart-lab/task-four-point-trend",
    previewHref: "/chart-lab/demo-phase1-phase2",
    prerequisites: ["node-lesson-phase1-phase2"],
    unlocks: [],
    xpReward: 40,
    stageId: "stage-positioning",
  },
  {
    id: "node-quiz-positioning",
    slug: "positioning-check",
    title: "Positioning Check",
    type: "quiz",
    level: "advanced",
    refId: "pf-m2-quiz",
    href: "/paths/professional-forex/lessons/positioning-check",
    prerequisites: ["node-lesson-phase1-phase2"],
    unlocks: ["node-lesson-strategy-selection"],
    xpReward: 50,
    stageId: "stage-positioning",
  },
  {
    id: "node-lesson-strategy-selection",
    slug: "strategy-selection-not-collecting",
    title: "Strategy Selection, Not Collecting",
    type: "lesson",
    level: "advanced",
    refId: "pf-m3-selection-not-collecting",
    href: "/paths/professional-forex/lessons/strategy-selection-not-collecting",
    prerequisites: ["node-quiz-positioning"],
    unlocks: ["node-lesson-decision-engine"],
    xpReward: 35,
    stageId: "stage-strategy-selection",
  },
  {
    id: "node-lesson-decision-engine",
    slug: "trade-or-skip-decision-engine",
    title: "The Trade-or-Skip Decision Engine",
    type: "lesson",
    level: "advanced",
    refId: "pf-m3-decision-engine",
    href: "/paths/professional-forex/lessons/trade-or-skip-decision-engine",
    prerequisites: ["node-lesson-strategy-selection"],
    unlocks: ["node-chart-pullback-continuation", "node-quiz-strategy-selection"],
    xpReward: 35,
    stageId: "stage-strategy-selection",
  },
  {
    id: "node-chart-pullback-continuation",
    slug: "pullback-continuation",
    title: "Trade the Phase 1 Resumption",
    type: "chart-drill",
    level: "advanced",
    refId: "task-pullback-continuation",
    href: "/chart-lab/task-pullback-continuation",
    previewHref: "/chart-lab/demo-pullback-support",
    prerequisites: ["node-lesson-decision-engine"],
    unlocks: [],
    xpReward: 45,
    stageId: "stage-strategy-selection",
  },
  {
    id: "node-quiz-strategy-selection",
    slug: "strategy-selection-check",
    title: "Strategy Selection Check",
    type: "quiz",
    level: "advanced",
    refId: "pf-m3-quiz",
    href: "/paths/professional-forex/lessons/strategy-selection-check",
    prerequisites: ["node-lesson-decision-engine"],
    unlocks: ["node-lesson-watchlist"],
    xpReward: 50,
    stageId: "stage-strategy-selection",
  },
  {
    id: "node-lesson-watchlist",
    slug: "why-professionals-dont-trade-every-pair",
    title: "Why Professionals Don't Trade Every Pair",
    type: "lesson",
    level: "advanced",
    refId: "pf-m4-not-every-pair",
    href: "/paths/professional-forex/lessons/why-professionals-dont-trade-every-pair",
    prerequisites: ["node-quiz-strategy-selection"],
    unlocks: ["node-lesson-pair-scoring"],
    xpReward: 35,
    stageId: "stage-watchlist",
  },
  {
    id: "node-lesson-pair-scoring",
    slug: "pair-scoring",
    title: "Pair Scoring",
    type: "lesson",
    level: "advanced",
    refId: "pf-m4-pair-scoring",
    href: "/paths/professional-forex/lessons/pair-scoring",
    prerequisites: ["node-lesson-watchlist"],
    unlocks: ["node-quiz-watchlist"],
    xpReward: 35,
    stageId: "stage-watchlist",
  },
  {
    id: "node-quiz-watchlist",
    slug: "watchlist-check",
    title: "Watchlist Check",
    type: "quiz",
    level: "advanced",
    refId: "pf-m4-quiz",
    href: "/paths/professional-forex/lessons/watchlist-check",
    prerequisites: ["node-lesson-pair-scoring"],
    unlocks: ["node-lesson-daily-routine"],
    xpReward: 50,
    stageId: "stage-watchlist",
  },
  {
    id: "node-lesson-daily-routine",
    slug: "daily-trading-routine",
    title: "The Daily Trading Routine",
    type: "lesson",
    level: "advanced",
    refId: "pf-m5-daily-routine",
    href: "/paths/professional-forex/lessons/daily-trading-routine",
    prerequisites: ["node-quiz-watchlist"],
    unlocks: ["node-lesson-risk-rules"],
    xpReward: 35,
    stageId: "stage-operating-system",
  },
  {
    id: "node-lesson-risk-rules",
    slug: "professional-risk-rules",
    title: "Professional Risk Rules",
    type: "lesson",
    level: "advanced",
    refId: "pf-m5-risk-rules",
    href: "/paths/professional-forex/lessons/professional-risk-rules",
    prerequisites: ["node-lesson-daily-routine"],
    unlocks: ["node-flashcards-professional", "node-quiz-professional-assessment"],
    xpReward: 35,
    stageId: "stage-operating-system",
  },
  {
    id: "node-flashcards-professional",
    slug: "professional-forex-deck",
    title: "Professional Forex Flashcards",
    type: "flashcard-deck",
    level: "advanced",
    refId: "deck-professional-forex",
    href: "/flashcards/session?deck=professional-forex",
    prerequisites: ["node-lesson-risk-rules"],
    unlocks: [],
    xpReward: 25,
    stageId: "stage-operating-system",
  },
  {
    id: "node-quiz-professional-assessment",
    slug: "professional-forex-workflow-assessment",
    title: "Professional Forex Workflow Assessment",
    type: "quiz",
    level: "advanced",
    refId: "pf-m5-final-assessment",
    href: "/paths/professional-forex/lessons/professional-forex-workflow-assessment",
    prerequisites: ["node-lesson-risk-rules"],
    unlocks: [],
    xpReward: 100,
    stageId: "stage-operating-system",
  },
  // ---- Full-path optional nodes (Forex Basics, Risk Management, Psychology) ----
  {
    id: "node-lesson-what-is-forex",
    slug: "what-is-forex",
    title: "What Is Forex? (Forex Basics)",
    type: "lesson",
    level: "beginner",
    refId: "fxb-m1-what-is-forex",
    href: "/paths/forex-basics/lessons/what-is-forex",
    prerequisites: [],
    unlocks: [],
    xpReward: 25,
    stageId: "stage-market-basics",
  },
  {
    id: "node-lesson-position-sizing",
    slug: "position-sizing-formula",
    title: "The Position Sizing Formula",
    type: "lesson",
    level: "intermediate",
    refId: "rm-m2-sizing-formula",
    href: "/paths/risk-management/lessons/the-position-sizing-formula",
    prerequisites: ["node-lesson-risk-reward"],
    unlocks: [],
    xpReward: 35,
    stageId: "stage-risk-management",
  },
  {
    id: "node-lesson-trade-wait-skip",
    slug: "trade-wait-skip",
    title: "Trade, Wait, Skip",
    type: "lesson",
    level: "intermediate",
    refId: "tp-m5-trade-wait-skip",
    href: "/paths/trading-psychology/lessons/trade-wait-skip",
    prerequisites: ["node-journal-first"],
    unlocks: [],
    xpReward: 35,
    stageId: "stage-psychology-journaling",
  },
  {
    id: "node-lesson-market-structure",
    slug: "what-is-market-structure",
    title: "Market Structure Mastery",
    type: "lesson",
    level: "beginner",
    refId: "ms-what-is-structure",
    href: "/paths/market-structure-mastery/lessons/what-is-market-structure",
    prerequisites: ["node-lesson-swing-highs"],
    unlocks: [],
    xpReward: 30,
    stageId: "stage-market-structure",
  },
]

export const NODE_BY_ID = Object.fromEntries(
  LEARNING_NODES.map((n) => [n.id, n])
) as Record<string, LearningNode>

export function getNodeById(id: string): LearningNode | undefined {
  return NODE_BY_ID[id]
}
