import type { LearningStage } from "@/lib/learning-map/types"

export const LEARNING_STAGES: LearningStage[] = [
  {
    id: "stage-market-basics",
    slug: "market-basics",
    title: "Market Basics",
    description: "What trading is, how markets move, and why practice comes first.",
    order: 1,
    level: "beginner",
    stageType: "foundation",
    prerequisiteStageIds: [],
    requiredNodeIds: [
      "node-lesson-what-is-trading",
      "node-lesson-what-moves-price",
      "node-quiz-basics",
    ],
    optionalNodeIds: [],
    unlockNodeIds: ["node-lesson-candle-anatomy"],
    unlockFeatureIds: ["feature-book-lab-starter"],
    skillsGained: ["What is trading", "Buyers vs sellers", "Volatility basics"],
    estimatedMinutes: 25,
    href: "/paths/trading-foundations/lessons/what-is-trading",
  },
  {
    id: "stage-candlesticks",
    slug: "candlesticks",
    title: "Candlesticks",
    description: "Read open, high, low, close — the language of price.",
    order: 2,
    level: "beginner",
    stageType: "foundation",
    prerequisiteStageIds: ["stage-market-basics"],
    requiredNodeIds: [
      "node-lesson-candle-anatomy",
      "node-lesson-bullish-bearish",
      "node-quiz-candles",
    ],
    optionalNodeIds: [],
    unlockNodeIds: ["node-lesson-swing-highs"],
    unlockFeatureIds: ["feature-flashcards-candlesticks"],
    skillsGained: ["Candle body", "Wicks", "Bullish vs bearish"],
    estimatedMinutes: 20,
    href: "/paths/trading-foundations/lessons/candlestick-anatomy",
  },
  {
    id: "stage-market-structure",
    slug: "market-structure",
    title: "Market Structure",
    description: "Swing highs, swing lows, and the building blocks of trend.",
    order: 3,
    level: "beginner",
    stageType: "visual",
    prerequisiteStageIds: ["stage-candlesticks"],
    requiredNodeIds: [
      "node-lesson-swing-highs",
      "node-lesson-trends-ranges",
    ],
    optionalNodeIds: ["node-drill-spot-trend"],
    unlockNodeIds: ["node-trend-what-is"],
    unlockFeatureIds: ["feature-chart-lab-swings"],
    skillsGained: ["Swing highs", "Swing lows", "Trend vs range"],
    estimatedMinutes: 30,
    href: "/paths/trading-foundations/lessons/swing-highs-and-lows",
  },
  {
    id: "stage-trend-detection",
    slug: "trend-detection",
    title: "Trend Detection",
    description: "Spot uptrends, downtrends, ranges, and messy no-trade charts.",
    order: 4,
    level: "beginner-plus",
    stageType: "practice",
    prerequisiteStageIds: ["stage-market-structure"],
    requiredNodeIds: [
      "node-trend-what-is",
      "node-trend-up-vs-down",
      "node-trend-vs-range",
    ],
    optionalNodeIds: [],
    unlockNodeIds: ["node-trend-challenge"],
    unlockFeatureIds: ["feature-trend-spotter-challenge"],
    skillsGained: ["Uptrend", "Downtrend", "Range", "Messy chart skip"],
    estimatedMinutes: 35,
    href: "/trend-spotter/lessons/what-is-a-trend",
  },
  {
    id: "stage-support-resistance",
    slug: "support-resistance",
    title: "Support & Resistance",
    description: "Mark levels where price repeatedly reacts.",
    order: 5,
    level: "beginner-plus",
    stageType: "visual",
    prerequisiteStageIds: ["stage-trend-detection"],
    requiredNodeIds: ["node-chart-support", "node-chart-resistance"],
    optionalNodeIds: [],
    unlockNodeIds: ["node-strategy-support-bounce"],
    unlockFeatureIds: ["feature-strategy-sr", "feature-chart-lab-levels"],
    skillsGained: ["Support zones", "Resistance zones", "Level flips"],
    estimatedMinutes: 25,
    href: "/chart-lab/task-identify-support",
  },
  {
    id: "stage-breakouts-fakeouts",
    slug: "breakouts-fakeouts",
    title: "Breakouts & Fakeouts",
    description: "When price breaks a level — and when the break fails.",
    order: 6,
    level: "intermediate",
    stageType: "practice",
    prerequisiteStageIds: ["stage-support-resistance"],
    requiredNodeIds: ["node-chart-breakout", "node-chart-fakeout"],
    optionalNodeIds: [],
    unlockNodeIds: ["node-strategy-break-retest"],
    unlockFeatureIds: ["feature-strategy-break-retest"],
    skillsGained: ["Breakouts", "Fakeouts", "Confirmation"],
    estimatedMinutes: 30,
    href: "/chart-lab/demo-breakout",
  },
  {
    id: "stage-risk-management",
    slug: "risk-management",
    title: "Risk Management",
    description: "Risk per trade, stops, targets, and protecting the account.",
    order: 7,
    level: "beginner",
    stageType: "foundation",
    prerequisiteStageIds: ["stage-market-structure"],
    requiredNodeIds: [
      "node-lesson-what-is-risk",
      "node-lesson-risk-reward",
      "node-book-risk-reward",
    ],
    optionalNodeIds: ["node-lesson-interactive-rr"],
    unlockNodeIds: [],
    unlockFeatureIds: ["feature-strategy-intermediate"],
    skillsGained: ["Risk/reward", "Stop loss", "Position sizing mindset"],
    estimatedMinutes: 35,
    href: "/paths/trading-foundations/lessons/what-is-risk",
  },
  {
    id: "stage-break-retest",
    slug: "break-retest",
    title: "Break & Retest",
    description: "Your first repeatable setup — break, retest, continue.",
    order: 8,
    level: "intermediate",
    stageType: "strategy",
    prerequisiteStageIds: ["stage-breakouts-fakeouts", "stage-risk-management"],
    requiredNodeIds: [
      "node-strategy-break-retest",
      "node-strategy-break-retest-practice",
    ],
    optionalNodeIds: [],
    unlockNodeIds: ["node-flashcards-break-retest"],
    unlockFeatureIds: ["feature-strategy-wiki-practice"],
    skillsGained: ["Break & retest", "Retest confirmation", "Invalidation"],
    estimatedMinutes: 40,
    href: "/strategy-wiki/break-retest",
  },
  {
    id: "stage-icc-foundations",
    slug: "icc-foundations",
    title: "ICC Foundations",
    description: "Indication, correction, continuation — structured trend trading.",
    order: 9,
    level: "intermediate",
    stageType: "strategy",
    prerequisiteStageIds: ["stage-trend-detection", "stage-break-retest"],
    requiredNodeIds: [
      "node-lesson-icc-indication",
      "node-strategy-icc",
    ],
    optionalNodeIds: [],
    unlockNodeIds: [],
    unlockFeatureIds: ["feature-icc-chart-lab"],
    skillsGained: ["ICC phases", "HTF bias", "Continuation triggers"],
    estimatedMinutes: 45,
    href: "/paths/icc-strategy/lessons/indication",
  },
  {
    id: "stage-strategy-practice",
    slug: "strategy-practice",
    title: "Strategy Practice",
    description: "Apply setups step by step with chart markup and challenges.",
    order: 10,
    level: "intermediate",
    stageType: "strategy",
    prerequisiteStageIds: ["stage-break-retest"],
    requiredNodeIds: ["node-strategy-support-bounce", "node-strategy-challenge"],
    optionalNodeIds: [],
    unlockNodeIds: [],
    unlockFeatureIds: ["feature-strategy-all-beginner"],
    skillsGained: ["Setup planning", "Trade or skip", "Strategy repetition"],
    estimatedMinutes: 50,
    href: "/strategy-wiki/support-bounce/practice",
  },
  {
    id: "stage-psychology-journaling",
    slug: "psychology-journaling",
    title: "Psychology & Journaling",
    description: "Discipline, reflection, and learning from your practice.",
    order: 11,
    level: "beginner-plus",
    stageType: "psychology",
    prerequisiteStageIds: ["stage-risk-management"],
    requiredNodeIds: [
      "node-journal-first",
      "node-lesson-reflection",
      "node-book-psychology",
    ],
    optionalNodeIds: [],
    unlockNodeIds: [],
    unlockFeatureIds: ["feature-journal-full"],
    skillsGained: ["Journaling", "Mistake tags", "Confidence rating"],
    estimatedMinutes: 25,
    href: "/journal",
  },
  {
    id: "stage-intermediate-mastery",
    slug: "intermediate-mastery",
    title: "Intermediate Chart Mastery",
    description: "Combine trend, levels, and setups under time pressure.",
    order: 12,
    level: "advanced",
    stageType: "mastery",
    prerequisiteStageIds: [
      "stage-strategy-practice",
      "stage-psychology-journaling",
    ],
    requiredNodeIds: [
      "node-trend-challenge",
      "node-flashcards-mastery",
      "node-strategy-challenge-advanced",
    ],
    optionalNodeIds: [],
    unlockNodeIds: [],
    unlockFeatureIds: ["feature-exploration-full"],
    skillsGained: ["Pattern speed", "Multi-setup recognition", "Consistent review"],
    estimatedMinutes: 60,
    href: "/trend-spotter/challenge",
  },
]
