import { buildConcept } from "@/content/book-lab/concept-builder"
import type { BookLabConcept } from "@/lib/book-lab/types"

const SECTION = "bl-core-strategies"

export const coreStrategiesConcepts: BookLabConcept[] = [
  buildConcept({
    slug: "momentum-trading",
    sectionId: SECTION,
    title: "Momentum Trading",
    summary: "Trade strong directional moves with volume — ride strength, don't fight it early.",
    explanation:
      "Momentum traders buy strength and sell weakness in names in play. They use tight risk when trend pauses and avoid catching falling knives without reversal proof.",
    whyMatters: "Many day-trading styles start with reading momentum.",
    commonMistake: "Shorting strong leaders with no reversal signal.",
    chartDemoId: "demo-bullish-bearish",
    reflectionPrompt: "Will you trade with momentum or fade it while learning?",
    relatedConceptSlugs: ["bull-flag", "high-of-day-breakout"],
    quizQuestions: [{
      question: "Momentum trading focuses on:",
      options: [
        { id: "a", text: "Strong moves with participation" },
        { id: "b", text: "Only flat charts" },
        { id: "c", text: "Guaranteed reversals" },
        { id: "d", text: "Ignoring volume" },
      ],
      correctAnswer: "a",
      explanation: "Momentum needs direction and volume.",
    }],
  }),
  buildConcept({
    slug: "bull-flag",
    sectionId: SECTION,
    title: "Bull Flag",
    summary: "Sharp rally (pole), tight pullback (flag), continuation breakout.",
    explanation:
      "Bull flags show strong impulse up, then orderly pullback on lighter volume. Entry often triggers on break of flag high with stop below flag low.",
    whyMatters: "Classic continuation pattern on momentum leaders.",
    commonMistake: "Buying mid-flag with no breakout trigger.",
    chartDemoId: "demo-bull-flag",
    chartPracticeId: "task-icc-bullish",
    reflectionPrompt: "Where is your stop on a bull flag — below flag or below pole?",
    relatedConceptSlugs: ["momentum-trading", "support-resistance-strategy"],
    quizQuestions: [{
      question: "A bull flag typically has:",
      options: [
        { id: "a", text: "Strong pole, shallow pullback, continuation" },
        { id: "b", text: "No volume ever" },
        { id: "c", text: "Only bearish candles" },
        { id: "d", text: "Guaranteed failure" },
      ],
      correctAnswer: "a",
      explanation: "Pole-flag-continue is the classic shape.",
    }],
  }),
  buildConcept({
    slug: "reversal-trading",
    sectionId: SECTION,
    title: "Reversal Trading",
    summary: "Trade exhaustion after extended moves — higher skill, tighter risk.",
    explanation:
      "Reversals hunt climactic volume, failed breakouts, or loss of trend structure. Beginners should master continuation before fading strong trends.",
    whyMatters: "Fades offer R:R but fail badly if trend continues.",
    commonMistake: "Picking tops on leaders still making higher highs.",
    chartDemoId: "demo-fakeout",
    reflectionPrompt: "What signal would prove exhaustion for you?",
    relatedConceptSlugs: ["failed-breakout", "support-resistance-strategy"],
    quizQuestions: [{
      question: "Reversal setups need:",
      options: [
        { id: "a", text: "Evidence trend is exhausting or failing" },
        { id: "b", text: "Only a green candle" },
        { id: "c", text: "No stop loss" },
        { id: "d", text: "Maximum size always" },
      ],
      correctAnswer: "a",
      explanation: "Fades require proof, not hope.",
    }],
  }),
  buildConcept({
    slug: "moving-average-trend",
    sectionId: SECTION,
    title: "Moving Average Trend Strategy",
    summary: "Use MAs as dynamic support/resistance in trending names.",
    explanation:
      "Common intraday MAs (9, 20, 200) act as guides. In uptrends, pullbacks to rising MAs can offer long entries with stops below. Ranging markets whipsaw MA systems.",
    whyMatters: "MAs simplify trend context for beginners.",
    commonMistake: "Trading MA bounces in choppy, range-bound charts.",
    chartDemoId: "demo-trend-range",
    chartPracticeId: "task-spot-trend",
    reflectionPrompt: "Which MA period will you test first on intraday charts?",
    relatedConceptSlugs: ["vwap-strategy", "momentum-trading"],
    quizQuestions: [{
      question: "MA trend strategy works best when:",
      options: [
        { id: "a", text: "Price trends cleanly above/below the MA" },
        { id: "b", text: "Market is choppy with no direction" },
        { id: "c", text: "Volume is zero" },
        { id: "d", text: "Stops are removed" },
      ],
      correctAnswer: "a",
      explanation: "Trending conditions suit MA guides.",
    }],
  }),
  buildConcept({
    slug: "vwap-strategy",
    sectionId: SECTION,
    title: "VWAP Strategy",
    summary: "Volume-weighted average price — intraday fair value anchor.",
    explanation:
      "VWAP resets each session. Above VWAP suggests bullish control; below suggests bearish. Traders look for bounces, rejections, and mean reversion around VWAP on active names.",
    whyMatters: "Widely watched on institutional timeframes.",
    commonMistake: "Treating VWAP as magic support without volume context.",
    chartDemoId: "demo-vwap-bounce",
    reflectionPrompt: "Will you use VWAP for bias, entries, or both?",
    relatedConceptSlugs: ["moving-average-trend", "support-resistance-strategy"],
    quizQuestions: [{
      question: "VWAP represents:",
      options: [
        { id: "a", text: "Average price weighted by volume today" },
        { id: "b", text: "Yesterday's close only" },
        { id: "c", text: "Guaranteed reversal level" },
        { id: "d", text: "Broker commission" },
      ],
      correctAnswer: "a",
      explanation: "VWAP is session volume-weighted average price.",
    }],
  }),
  buildConcept({
    slug: "support-resistance-strategy",
    sectionId: SECTION,
    title: "Support & Resistance Strategy",
    summary: "Trade reactions at levels where price repeatedly turned.",
    explanation:
      "Support is a floor; resistance is a ceiling. Breakouts, bounces, and retests at these levels form many day-trading setups.",
    whyMatters: "Levels frame entries, stops, and targets.",
    commonMistake: "Drawing too many lines and trading all of them.",
    chartDemoId: "demo-support",
    chartPracticeId: "task-identify-support",
    reflectionPrompt: "How many key levels will you mark per chart?",
    relatedConceptSlugs: ["opening-range-breakout", "vwap-strategy"],
    quizQuestions: [{
      question: "Support is:",
      options: [
        { id: "a", text: "A zone where buyers repeatedly defend price" },
        { id: "b", text: "A guarantee price cannot fall" },
        { id: "c", text: "Only on weekly charts" },
        { id: "d", text: "Unrelated to day trading" },
      ],
      correctAnswer: "a",
      explanation: "Support is defended demand, not a promise.",
    }],
  }),
  buildConcept({
    slug: "opening-range-breakout",
    sectionId: SECTION,
    title: "Opening Range Breakout",
    summary: "Trade break of the first N minutes' high or low with volume.",
    explanation:
      "Mark opening range (e.g. first 5–15 minutes). Break above with volume can signal continuation; break below can signal failure. Need catalyst and liquid name.",
    whyMatters: "Popular open strategy when gap names establish range.",
    commonMistake: "Trading ORB on dead tickers with no volume.",
    chartDemoId: "demo-opening-range",
    chartPracticeId: "task-mark-breakout",
    reflectionPrompt: "How many minutes will define your opening range?",
    relatedConceptSlugs: ["gappers", "momentum-trading"],
    quizQuestions: [{
      question: "Opening range breakout needs:",
      options: [
        { id: "a", text: "Defined range, break, and volume confirmation" },
        { id: "b", text: "No plan at all" },
        { id: "c", text: "Only after market close" },
        { id: "d", text: "Removed stops" },
      ],
      correctAnswer: "a",
      explanation: "Range, break, and participation define ORB.",
    }],
  }),
  buildConcept({
    slug: "high-of-day-breakout",
    sectionId: SECTION,
    title: "High of Day Breakout",
    summary: "Buy break of session high on momentum leaders; stop below structure.",
    explanation:
      "HOD breakouts ride strength when new buyers chase breakout above prior high. Requires liquid ticker and defined risk — extended moves fail without volume.",
    whyMatters: "Common momentum continuation trigger.",
    commonMistake: "Chasing HOD break far from support with poor R:R.",
    chartDemoId: "demo-breakout",
    chartPracticeId: "task-mark-breakout",
    reflectionPrompt: "What minimum R:R will you require on HOD breaks?",
    relatedConceptSlugs: ["momentum-trading", "avoid-chasing"],
    quizQuestions: [{
      question: "HOD breakout is:",
      options: [
        { id: "a", text: "Entry on break above session high" },
        { id: "b", text: "Guaranteed all-day rally" },
        { id: "c", text: "Only for investing" },
        { id: "d", text: "Trade without stops" },
      ],
      correctAnswer: "a",
      explanation: "HOD break is a momentum trigger, not a guarantee.",
    }],
  }),
  buildConcept({
    slug: "failed-breakout",
    sectionId: SECTION,
    title: "Failed Breakout",
    summary: "Price breaks a level then closes back inside — trap for breakout buyers.",
    explanation:
      "Failed breakouts (fakeouts) often reverse sharply. Fade traders wait for close back inside range with volume drying up on the extension.",
    whyMatters: "Recognizing failures avoids chasing and enables fades.",
    commonMistake: "Holding long after obvious fakeout close.",
    chartDemoId: "demo-fakeout",
    reflectionPrompt: "How will you tell breakout from fakeout?",
    relatedConceptSlugs: ["reversal-trading", "wait-for-confirmation"],
    quizQuestions: [{
      question: "Failed breakout often shows:",
      options: [
        { id: "a", text: "Close back inside the broken level" },
        { id: "b", text: "Infinite continuation" },
        { id: "c", text: "Zero volume on reversal" },
        { id: "d", text: "No relevance to day trading" },
      ],
      correctAnswer: "a",
      explanation: "Close back inside invalidates the break.",
    }],
  }),
]
